# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mirror_detect/HubServiceRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class HubServiceRequest(genpy.Message):
  _md5sum = "093b75730440a09d8b70709532b709f2"
  _type = "mirror_detect/HubServiceRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose pose_target
bool enable_detect
bool use_scan_merge
float32 length

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['pose_target','enable_detect','use_scan_merge','length']
  _slot_types = ['geometry_msgs/Pose','bool','bool','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pose_target,enable_detect,use_scan_merge,length

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HubServiceRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pose_target is None:
        self.pose_target = geometry_msgs.msg.Pose()
      if self.enable_detect is None:
        self.enable_detect = False
      if self.use_scan_merge is None:
        self.use_scan_merge = False
      if self.length is None:
        self.length = 0.
    else:
      self.pose_target = geometry_msgs.msg.Pose()
      self.enable_detect = False
      self.use_scan_merge = False
      self.length = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d2Bf().pack(_x.pose_target.position.x, _x.pose_target.position.y, _x.pose_target.position.z, _x.pose_target.orientation.x, _x.pose_target.orientation.y, _x.pose_target.orientation.z, _x.pose_target.orientation.w, _x.enable_detect, _x.use_scan_merge, _x.length))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose_target is None:
        self.pose_target = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 62
      (_x.pose_target.position.x, _x.pose_target.position.y, _x.pose_target.position.z, _x.pose_target.orientation.x, _x.pose_target.orientation.y, _x.pose_target.orientation.z, _x.pose_target.orientation.w, _x.enable_detect, _x.use_scan_merge, _x.length,) = _get_struct_7d2Bf().unpack(str[start:end])
      self.enable_detect = bool(self.enable_detect)
      self.use_scan_merge = bool(self.use_scan_merge)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d2Bf().pack(_x.pose_target.position.x, _x.pose_target.position.y, _x.pose_target.position.z, _x.pose_target.orientation.x, _x.pose_target.orientation.y, _x.pose_target.orientation.z, _x.pose_target.orientation.w, _x.enable_detect, _x.use_scan_merge, _x.length))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose_target is None:
        self.pose_target = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 62
      (_x.pose_target.position.x, _x.pose_target.position.y, _x.pose_target.position.z, _x.pose_target.orientation.x, _x.pose_target.orientation.y, _x.pose_target.orientation.z, _x.pose_target.orientation.w, _x.enable_detect, _x.use_scan_merge, _x.length,) = _get_struct_7d2Bf().unpack(str[start:end])
      self.enable_detect = bool(self.enable_detect)
      self.use_scan_merge = bool(self.use_scan_merge)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d2Bf = None
def _get_struct_7d2Bf():
    global _struct_7d2Bf
    if _struct_7d2Bf is None:
        _struct_7d2Bf = struct.Struct("<7d2Bf")
    return _struct_7d2Bf
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mirror_detect/HubServiceResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class HubServiceResponse(genpy.Message):
  _md5sum = "358e233cde0c8a8bcfea4ce193f8fc15"
  _type = "mirror_detect/HubServiceResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool success
"""
  __slots__ = ['success']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HubServiceResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
    else:
      self.success = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.success
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _get_struct_B().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.success
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _get_struct_B().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class HubService(object):
  _type          = 'mirror_detect/HubService'
  _md5sum = 'af013932b4bc2657d1c28aa1d3ac1eb6'
  _request_class  = HubServiceRequest
  _response_class = HubServiceResponse
