# Config for Lift 2 (far distance, wider tolerances)
RS_max_iter: 252
RS_min_inliers: 2
RS_dist_thresh: 0.025
RANSAC_on_clusters: True
Voxel_leaf_size: 0.001
EC_cluster_tolerance: 0.05
EC_min_size: 2
EC_max_size: 60
laser_frame: "laser"
robot_frame: "base_link"
#Bar marker detection
BAR_length: 0.033 # length of mirror
BAR_length_tolerance: 0.053
BAR_distance: 1.6 # distance detect from x coord
BAR_distance_tolerance: 0.1
Leg_length: 0.88 # length of 2 leg beetwen 2 mirror
Leg_tolerance: 0.5
#ICP detection
mirror_type: 1 # 0-line 1-circle
radius_detect: 0.45
icp_type: 2 # 0 = circle 1 = point cloud 2 = point
max_intensity_time: 3.3
max_cluster_size: 1.85
intensity_times: 1.2
max_dis_discard: 0.5
mirror_point_publish: 1
publish_scan: True
use_laser: true
use_diff_laser: false
intensity_range: "/home/mkac/mav_ws/src/mirror_detect/config/intensity_range_richbeam.yaml"
scan_mirror_topic_: "scan_mirror"
