points:
  - distance: 0.0
    intensity_discard: 235
    radius_tolerance: 0.02
    
  - distance: 5.0
    intensity_discard: 1000 
    radius_tolerance: 0.023
  - distance: 10.0
    intensity_discard: 300
    radius_tolerance: 0.023

