// Generated by gencpp from file cognex_qr_code/QrCodeRequest.msg
// DO NOT EDIT!


#ifndef COGNEX_QR_CODE_MESSAGE_QRCODEREQUEST_H
#define COGNEX_QR_CODE_MESSAGE_QRCODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cognex_qr_code
{
template <class ContainerAllocator>
struct QrCodeRequest_
{
  typedef QrCodeRequest_<ContainerAllocator> Type;

  QrCodeRequest_()
    : TimeOut(0)  {
    }
  QrCodeRequest_(const ContainerAllocator& _alloc)
    : TimeOut(0)  {
  (void)_alloc;
    }



   typedef int8_t _TimeOut_type;
  _TimeOut_type TimeOut;





  typedef boost::shared_ptr< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QrCodeRequest_

typedef ::cognex_qr_code::QrCodeRequest_<std::allocator<void> > QrCodeRequest;

typedef boost::shared_ptr< ::cognex_qr_code::QrCodeRequest > QrCodeRequestPtr;
typedef boost::shared_ptr< ::cognex_qr_code::QrCodeRequest const> QrCodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cognex_qr_code::QrCodeRequest_<ContainerAllocator1> & lhs, const ::cognex_qr_code::QrCodeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.TimeOut == rhs.TimeOut;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cognex_qr_code::QrCodeRequest_<ContainerAllocator1> & lhs, const ::cognex_qr_code::QrCodeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cognex_qr_code

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d24a691b70fc267c6fc5116b95e671e";
  }

  static const char* value(const ::cognex_qr_code::QrCodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d24a691b70fc267ULL;
  static const uint64_t static_value2 = 0xc6fc5116b95e671eULL;
};

template<class ContainerAllocator>
struct DataType< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cognex_qr_code/QrCodeRequest";
  }

  static const char* value(const ::cognex_qr_code::QrCodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 TimeOut\n"
;
  }

  static const char* value(const ::cognex_qr_code::QrCodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TimeOut);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QrCodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cognex_qr_code::QrCodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cognex_qr_code::QrCodeRequest_<ContainerAllocator>& v)
  {
    s << indent << "TimeOut: ";
    Printer<int8_t>::stream(s, indent + "  ", v.TimeOut);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COGNEX_QR_CODE_MESSAGE_QRCODEREQUEST_H
