// Generated by gencpp from file docking/DockServiceRequest.msg
// DO NOT EDIT!


#ifndef DOCKING_MESSAGE_DOCKSERVICEREQUEST_H
#define DOCKING_MESSAGE_DOCKSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace docking
{
template <class ContainerAllocator>
struct DockServiceRequest_
{
  typedef DockServiceRequest_<ContainerAllocator> Type;

  DockServiceRequest_()
    : pose_target()
    , enable_detect(false)
    , use_scan_merge(false)  {
    }
  DockServiceRequest_(const ContainerAllocator& _alloc)
    : pose_target(_alloc)
    , enable_detect(false)
    , use_scan_merge(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_target_type;
  _pose_target_type pose_target;

   typedef uint8_t _enable_detect_type;
  _enable_detect_type enable_detect;

   typedef uint8_t _use_scan_merge_type;
  _use_scan_merge_type use_scan_merge;





  typedef boost::shared_ptr< ::docking::DockServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::docking::DockServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DockServiceRequest_

typedef ::docking::DockServiceRequest_<std::allocator<void> > DockServiceRequest;

typedef boost::shared_ptr< ::docking::DockServiceRequest > DockServiceRequestPtr;
typedef boost::shared_ptr< ::docking::DockServiceRequest const> DockServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::docking::DockServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::docking::DockServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::docking::DockServiceRequest_<ContainerAllocator1> & lhs, const ::docking::DockServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose_target == rhs.pose_target &&
    lhs.enable_detect == rhs.enable_detect &&
    lhs.use_scan_merge == rhs.use_scan_merge;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::docking::DockServiceRequest_<ContainerAllocator1> & lhs, const ::docking::DockServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace docking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::docking::DockServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::docking::DockServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::docking::DockServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::docking::DockServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::docking::DockServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::docking::DockServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::docking::DockServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0d2310575e388a4e8074040e836bd0c";
  }

  static const char* value(const ::docking::DockServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0d2310575e388a4ULL;
  static const uint64_t static_value2 = 0xe8074040e836bd0cULL;
};

template<class ContainerAllocator>
struct DataType< ::docking::DockServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "docking/DockServiceRequest";
  }

  static const char* value(const ::docking::DockServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::docking::DockServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose_target\n"
"bool enable_detect\n"
"bool use_scan_merge\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::docking::DockServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::docking::DockServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_target);
      stream.next(m.enable_detect);
      stream.next(m.use_scan_merge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::docking::DockServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::docking::DockServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose_target: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_target);
    s << indent << "enable_detect: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_detect);
    s << indent << "use_scan_merge: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_scan_merge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOCKING_MESSAGE_DOCKSERVICEREQUEST_H
