//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the docking package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __docking__PLANNERNODECONFIG_H__
#define __docking__PLANNERNODECONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace docking
{
  class PlannerNodeConfigStatics;

  class PlannerNodeConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(PlannerNodeConfig &config, const PlannerNodeConfig &max, const PlannerNodeConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PlannerNodeConfig &config1, const PlannerNodeConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PlannerNodeConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PlannerNodeConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PlannerNodeConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PlannerNodeConfig &config) const = 0;
      virtual void getValue(const PlannerNodeConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T PlannerNodeConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T PlannerNodeConfig::* field;

      virtual void clamp(PlannerNodeConfig &config, const PlannerNodeConfig &max, const PlannerNodeConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PlannerNodeConfig &config1, const PlannerNodeConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PlannerNodeConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PlannerNodeConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PlannerNodeConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PlannerNodeConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PlannerNodeConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PlannerNodeConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PlannerNodeConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<PlannerNodeConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PlannerNodeConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("world_frame"==(*_i)->name){world_frame = boost::any_cast<std::string>(val);}
        if("robot_frame"==(*_i)->name){robot_frame = boost::any_cast<std::string>(val);}
        if("dock_frame"==(*_i)->name){dock_frame = boost::any_cast<std::string>(val);}
        if("dock_pose_topic"==(*_i)->name){dock_pose_topic = boost::any_cast<std::string>(val);}
        if("dock_gazebo_pose_topic"==(*_i)->name){dock_gazebo_pose_topic = boost::any_cast<std::string>(val);}
        if("use_calculated_pose"==(*_i)->name){use_calculated_pose = boost::any_cast<bool>(val);}
        if("goal_dist_tolerance"==(*_i)->name){goal_dist_tolerance = boost::any_cast<double>(val);}
        if("goal_orientation_tolerance"==(*_i)->name){goal_orientation_tolerance = boost::any_cast<double>(val);}
        if("use_steps"==(*_i)->name){use_steps = boost::any_cast<bool>(val);}
        if("path_steps"==(*_i)->name){path_steps = boost::any_cast<int>(val);}
        if("max_steps"==(*_i)->name){max_steps = boost::any_cast<int>(val);}
        if("time_step"==(*_i)->name){time_step = boost::any_cast<double>(val);}
        if("v"==(*_i)->name){v = boost::any_cast<double>(val);}
        if("omega_max"==(*_i)->name){omega_max = boost::any_cast<double>(val);}
        if("kPhi"==(*_i)->name){kPhi = boost::any_cast<double>(val);}
        if("kDelta"==(*_i)->name){kDelta = boost::any_cast<double>(val);}
        if("curvature_max"==(*_i)->name){curvature_max = boost::any_cast<double>(val);}
        if("beta"==(*_i)->name){beta = boost::any_cast<double>(val);}
        if("lambda"==(*_i)->name){lambda = boost::any_cast<double>(val);}
        if("entrance_dist"==(*_i)->name){entrance_dist = boost::any_cast<double>(val);}
        if("frequency"==(*_i)->name){frequency = boost::any_cast<int>(val);}
      }
    }

    std::string world_frame;
std::string robot_frame;
std::string dock_frame;
std::string dock_pose_topic;
std::string dock_gazebo_pose_topic;
bool use_calculated_pose;
double goal_dist_tolerance;
double goal_orientation_tolerance;
bool use_steps;
int path_steps;
int max_steps;
double time_step;
double v;
double omega_max;
double kPhi;
double kDelta;
double curvature_max;
double beta;
double lambda;
double entrance_dist;
int frequency;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string world_frame;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string robot_frame;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string dock_frame;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string dock_pose_topic;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string dock_gazebo_pose_topic;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_calculated_pose;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double goal_dist_tolerance;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double goal_orientation_tolerance;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_steps;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int path_steps;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_steps;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double time_step;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double v;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double omega_max;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double kPhi;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double kDelta;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double curvature_max;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double beta;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lambda;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double entrance_dist;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int frequency;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PlannerNodeConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PlannerNodeConfig &__max__ = __getMax__();
      const PlannerNodeConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PlannerNodeConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PlannerNodeConfig &__getDefault__();
    static const PlannerNodeConfig &__getMax__();
    static const PlannerNodeConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const PlannerNodeConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void PlannerNodeConfig::ParamDescription<std::string>::clamp(PlannerNodeConfig &config, const PlannerNodeConfig &max, const PlannerNodeConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class PlannerNodeConfigStatics
  {
    friend class PlannerNodeConfig;

    PlannerNodeConfigStatics()
    {
PlannerNodeConfig::GroupDescription<PlannerNodeConfig::DEFAULT, PlannerNodeConfig> Default("Default", "", 0, 0, true, &PlannerNodeConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.world_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.world_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.world_frame = "world";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<std::string>("world_frame", "str", 0, "Name of world frame", "", &PlannerNodeConfig::world_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<std::string>("world_frame", "str", 0, "Name of world frame", "", &PlannerNodeConfig::world_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.robot_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.robot_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.robot_frame = "base_link";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<std::string>("robot_frame", "str", 0, "Name of robot frame", "", &PlannerNodeConfig::robot_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<std::string>("robot_frame", "str", 0, "Name of robot frame", "", &PlannerNodeConfig::robot_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dock_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dock_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dock_frame = "dock_truth";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<std::string>("dock_frame", "str", 0, "Name of dock frame", "", &PlannerNodeConfig::dock_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<std::string>("dock_frame", "str", 0, "Name of dock frame", "", &PlannerNodeConfig::dock_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dock_pose_topic = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dock_pose_topic = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dock_pose_topic = "docking/dock_pose";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<std::string>("dock_pose_topic", "str", 0, "Topic of calculated dock pose", "", &PlannerNodeConfig::dock_pose_topic)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<std::string>("dock_pose_topic", "str", 0, "Topic of calculated dock pose", "", &PlannerNodeConfig::dock_pose_topic)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dock_gazebo_pose_topic = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dock_gazebo_pose_topic = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dock_gazebo_pose_topic = "dock_pose_gazebo";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<std::string>("dock_gazebo_pose_topic", "str", 0, "Topic of gazebo truth dock pose", "", &PlannerNodeConfig::dock_gazebo_pose_topic)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<std::string>("dock_gazebo_pose_topic", "str", 0, "Topic of gazebo truth dock pose", "", &PlannerNodeConfig::dock_gazebo_pose_topic)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_calculated_pose = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_calculated_pose = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_calculated_pose = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<bool>("use_calculated_pose", "bool", 0, "Switch between gazebo truth pose or calculated pose", "", &PlannerNodeConfig::use_calculated_pose)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<bool>("use_calculated_pose", "bool", 0, "Switch between gazebo truth pose or calculated pose", "", &PlannerNodeConfig::use_calculated_pose)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.goal_dist_tolerance = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.goal_dist_tolerance = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.goal_dist_tolerance = 0.03;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("goal_dist_tolerance", "double", 0, "Max Goal Distance Error Tolerance (m)", "", &PlannerNodeConfig::goal_dist_tolerance)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("goal_dist_tolerance", "double", 0, "Max Goal Distance Error Tolerance (m)", "", &PlannerNodeConfig::goal_dist_tolerance)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.goal_orientation_tolerance = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.goal_orientation_tolerance = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.goal_orientation_tolerance = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("goal_orientation_tolerance", "double", 0, "Max Goal Orientation Error Tolerance (rad)", "", &PlannerNodeConfig::goal_orientation_tolerance)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("goal_orientation_tolerance", "double", 0, "Max Goal Orientation Error Tolerance (rad)", "", &PlannerNodeConfig::goal_orientation_tolerance)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_steps = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_steps = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_steps = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<bool>("use_steps", "bool", 0, "Limit number of steps", "", &PlannerNodeConfig::use_steps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<bool>("use_steps", "bool", 0, "Limit number of steps", "", &PlannerNodeConfig::use_steps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.path_steps = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.path_steps = 369;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.path_steps = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<int>("path_steps", "int", 0, "Steps in pose path", "", &PlannerNodeConfig::path_steps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<int>("path_steps", "int", 0, "Steps in pose path", "", &PlannerNodeConfig::path_steps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_steps = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_steps = 10000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_steps = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<int>("max_steps", "int", 0, "Max steps in pose path", "", &PlannerNodeConfig::max_steps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<int>("max_steps", "int", 0, "Max steps in pose path", "", &PlannerNodeConfig::max_steps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.time_step = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.time_step = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.time_step = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("time_step", "double", 0, "Time per step in pose path", "", &PlannerNodeConfig::time_step)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("time_step", "double", 0, "Time per step in pose path", "", &PlannerNodeConfig::time_step)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.v = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.v = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.v = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("v", "double", 0, "Linear Velocity", "", &PlannerNodeConfig::v)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("v", "double", 0, "Linear Velocity", "", &PlannerNodeConfig::v)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.omega_max = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.omega_max = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.omega_max = 0.3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("omega_max", "double", 0, "Max Rotational Velocity", "", &PlannerNodeConfig::omega_max)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("omega_max", "double", 0, "Max Rotational Velocity", "", &PlannerNodeConfig::omega_max)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.kPhi = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.kPhi = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.kPhi = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("kPhi", "double", 0, "Rate of Change of Theta to R", "", &PlannerNodeConfig::kPhi)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("kPhi", "double", 0, "Rate of Change of Theta to R", "", &PlannerNodeConfig::kPhi)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.kDelta = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.kDelta = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.kDelta = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("kDelta", "double", 0, "Rate to Converge to Slow Subsystem", "", &PlannerNodeConfig::kDelta)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("kDelta", "double", 0, "Rate to Converge to Slow Subsystem", "", &PlannerNodeConfig::kDelta)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.curvature_max = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.curvature_max = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.curvature_max = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("curvature_max", "double", 0, "Max Curvature ", "", &PlannerNodeConfig::curvature_max)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("curvature_max", "double", 0, "Max Curvature ", "", &PlannerNodeConfig::curvature_max)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.beta = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.beta = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.beta = 0.2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("beta", "double", 0, "LinVel Gain Inversely Proportional to Curvature", "", &PlannerNodeConfig::beta)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("beta", "double", 0, "LinVel Gain Inversely Proportional to Curvature", "", &PlannerNodeConfig::beta)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lambda = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lambda = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lambda = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("lambda", "double", 0, "LinVel Gain Exponentially Inversely Proportional to Curvature", "", &PlannerNodeConfig::lambda)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("lambda", "double", 0, "LinVel Gain Exponentially Inversely Proportional to Curvature", "", &PlannerNodeConfig::lambda)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.entrance_dist = -0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.entrance_dist = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.entrance_dist = 0.3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("entrance_dist", "double", 0, "Distance to entrance checkpoint from inner dock", "", &PlannerNodeConfig::entrance_dist)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<double>("entrance_dist", "double", 0, "Distance to entrance checkpoint from inner dock", "", &PlannerNodeConfig::entrance_dist)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frequency = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frequency = 30;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frequency = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<int>("frequency", "int", 0, "Controller frequency", "", &PlannerNodeConfig::frequency)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PlannerNodeConfig::AbstractParamDescriptionConstPtr(new PlannerNodeConfig::ParamDescription<int>("frequency", "int", 0, "Controller frequency", "", &PlannerNodeConfig::frequency)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PlannerNodeConfig::AbstractGroupDescriptionConstPtr(new PlannerNodeConfig::GroupDescription<PlannerNodeConfig::DEFAULT, PlannerNodeConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<PlannerNodeConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<PlannerNodeConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PlannerNodeConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PlannerNodeConfig __max__;
    PlannerNodeConfig __min__;
    PlannerNodeConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PlannerNodeConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PlannerNodeConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PlannerNodeConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const PlannerNodeConfig &PlannerNodeConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const PlannerNodeConfig &PlannerNodeConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const PlannerNodeConfig &PlannerNodeConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<PlannerNodeConfig::AbstractParamDescriptionConstPtr> &PlannerNodeConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PlannerNodeConfig::AbstractGroupDescriptionConstPtr> &PlannerNodeConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PlannerNodeConfigStatics *PlannerNodeConfig::__get_statics__()
  {
    const static PlannerNodeConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PlannerNodeConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __PLANNERNODERECONFIGURATOR_H__
