// Generated by gencpp from file qr_irayble/CodeRead.msg
// DO NOT EDIT!


#ifndef QR_IRAYBLE_MESSAGE_CODEREAD_H
#define QR_IRAYBLE_MESSAGE_CODEREAD_H

#include <ros/service_traits.h>


#include <qr_irayble/CodeReadRequest.h>
#include <qr_irayble/CodeReadResponse.h>


namespace qr_irayble
{

struct CodeRead
{

typedef CodeReadRequest Request;
typedef CodeReadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CodeRead
} // namespace qr_irayble


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qr_irayble::CodeRead > {
  static const char* value()
  {
    return "67df3b6773c89deb64fbc2e4def3a244";
  }

  static const char* value(const ::qr_irayble::CodeRead&) { return value(); }
};

template<>
struct DataType< ::qr_irayble::CodeRead > {
  static const char* value()
  {
    return "qr_irayble/CodeRead";
  }

  static const char* value(const ::qr_irayble::CodeRead&) { return value(); }
};


// service_traits::MD5Sum< ::qr_irayble::CodeReadRequest> should match
// service_traits::MD5Sum< ::qr_irayble::CodeRead >
template<>
struct MD5Sum< ::qr_irayble::CodeReadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qr_irayble::CodeRead >::value();
  }
  static const char* value(const ::qr_irayble::CodeReadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qr_irayble::CodeReadRequest> should match
// service_traits::DataType< ::qr_irayble::CodeRead >
template<>
struct DataType< ::qr_irayble::CodeReadRequest>
{
  static const char* value()
  {
    return DataType< ::qr_irayble::CodeRead >::value();
  }
  static const char* value(const ::qr_irayble::CodeReadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qr_irayble::CodeReadResponse> should match
// service_traits::MD5Sum< ::qr_irayble::CodeRead >
template<>
struct MD5Sum< ::qr_irayble::CodeReadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qr_irayble::CodeRead >::value();
  }
  static const char* value(const ::qr_irayble::CodeReadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qr_irayble::CodeReadResponse> should match
// service_traits::DataType< ::qr_irayble::CodeRead >
template<>
struct DataType< ::qr_irayble::CodeReadResponse>
{
  static const char* value()
  {
    return DataType< ::qr_irayble::CodeRead >::value();
  }
  static const char* value(const ::qr_irayble::CodeReadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QR_IRAYBLE_MESSAGE_CODEREAD_H
