// Generated by gencpp from file qr_irayble/CodeReadRequest.msg
// DO NOT EDIT!


#ifndef QR_IRAYBLE_MESSAGE_CODEREADREQUEST_H
#define QR_IRAYBLE_MESSAGE_CODEREADREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qr_irayble
{
template <class ContainerAllocator>
struct CodeReadRequest_
{
  typedef CodeReadRequest_<ContainerAllocator> Type;

  CodeReadRequest_()
    : TimeOut(0)  {
    }
  CodeReadRequest_(const ContainerAllocator& _alloc)
    : TimeOut(0)  {
  (void)_alloc;
    }



   typedef int8_t _TimeOut_type;
  _TimeOut_type TimeOut;





  typedef boost::shared_ptr< ::qr_irayble::CodeReadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qr_irayble::CodeReadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CodeReadRequest_

typedef ::qr_irayble::CodeReadRequest_<std::allocator<void> > CodeReadRequest;

typedef boost::shared_ptr< ::qr_irayble::CodeReadRequest > CodeReadRequestPtr;
typedef boost::shared_ptr< ::qr_irayble::CodeReadRequest const> CodeReadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qr_irayble::CodeReadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qr_irayble::CodeReadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qr_irayble::CodeReadRequest_<ContainerAllocator1> & lhs, const ::qr_irayble::CodeReadRequest_<ContainerAllocator2> & rhs)
{
  return lhs.TimeOut == rhs.TimeOut;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qr_irayble::CodeReadRequest_<ContainerAllocator1> & lhs, const ::qr_irayble::CodeReadRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qr_irayble

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qr_irayble::CodeReadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qr_irayble::CodeReadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qr_irayble::CodeReadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qr_irayble::CodeReadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qr_irayble::CodeReadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qr_irayble::CodeReadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qr_irayble::CodeReadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d24a691b70fc267c6fc5116b95e671e";
  }

  static const char* value(const ::qr_irayble::CodeReadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d24a691b70fc267ULL;
  static const uint64_t static_value2 = 0xc6fc5116b95e671eULL;
};

template<class ContainerAllocator>
struct DataType< ::qr_irayble::CodeReadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qr_irayble/CodeReadRequest";
  }

  static const char* value(const ::qr_irayble::CodeReadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qr_irayble::CodeReadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 TimeOut\n"
;
  }

  static const char* value(const ::qr_irayble::CodeReadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qr_irayble::CodeReadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TimeOut);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CodeReadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qr_irayble::CodeReadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qr_irayble::CodeReadRequest_<ContainerAllocator>& v)
  {
    s << indent << "TimeOut: ";
    Printer<int8_t>::stream(s, indent + "  ", v.TimeOut);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QR_IRAYBLE_MESSAGE_CODEREADREQUEST_H
