(cl:in-package agv_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          EMG-VAL
          EMG
          START_1-VAL
          START_1
          START_2-VAL
          START_2
          STOP_1-VAL
          STOP_1
          STOP_2-VAL
          STOP_2
          REMOTE_A-VAL
          REMOTE_A
          REMOTE_B-VAL
          REMOTE_B
          MOTOR1_EN-VAL
          MOTOR1_EN
          MOTOR1_BREAK-VAL
          MOTOR1_BREAK
          MOTOR1_DIR-VAL
          MOTOR1_DIR
          MOTOR2_EN-VAL
          MOTOR2_EN
          MOTOR2_BREAK-VAL
          MOTOR2_BREAK
          MOTOR2_DIR-VAL
          MOTOR2_DIR
          BUMPER_1-VAL
          BUMPER_1
          BUMPER_2-VAL
          BUMPER_2
          LIFT_MAX-VAL
          LIFT_MAX
          LIFT_MIN-VAL
          LIFT_MIN
          AUTO_MAN_SW-VAL
          AUTO_MAN_SW
          RELEASE_MOTOR-VAL
          RELEASE_MOTOR
          BATTERY_1-VAL
          BATTERY_1
          BATTERY_2-VAL
          BATTERY_2
          BATTERY_3-VAL
          BATTERY_3
          BATTERY_4-VAL
          BATTERY_4
          CHARGING-VAL
          CHARGING
          ENCODER_LEFT-VAL
          ENCODER_LEFT
          ENCODER_RIGHT-VAL
          ENCODER_RIGHT
          SAFETY_1-VAL
          SAFETY_1
          SAFETY_2-VAL
          SAFETY_2
          SAFETY_3-VAL
          SAFETY_3
          SAFETY_4-VAL
          SAFETY_4
))