
(cl:in-package :asdf)

(defsystem "agv_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :geometry_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "ArduinoIO" :depends-on ("_package_ArduinoIO"))
    (:file "_package_ArduinoIO" :depends-on ("_package"))
    (:file "BasicFunction" :depends-on ("_package_BasicFunction"))
    (:file "_package_BasicFunction" :depends-on ("_package"))
    (:file "CardID" :depends-on ("_package_CardID"))
    (:file "_package_CardID" :depends-on ("_package"))
    (:file "CardWithFunction" :depends-on ("_package_CardWithFunction"))
    (:file "_package_CardWithFunction" :depends-on ("_package"))
    (:file "CartesianCoordinate" :depends-on ("_package_CartesianCoordinate"))
    (:file "_package_CartesianCoordinate" :depends-on ("_package"))
    (:file "CartesianPosition" :depends-on ("_package_CartesianPosition"))
    (:file "_package_CartesianPosition" :depends-on ("_package"))
    (:file "DataChanged" :depends-on ("_package_DataChanged"))
    (:file "_package_DataChanged" :depends-on ("_package"))
    (:file "DataMatrixStamped" :depends-on ("_package_DataMatrixStamped"))
    (:file "_package_DataMatrixStamped" :depends-on ("_package"))
    (:file "DiffDriverMotorSpeed" :depends-on ("_package_DiffDriverMotorSpeed"))
    (:file "_package_DiffDriverMotorSpeed" :depends-on ("_package"))
    (:file "DigitalSensor" :depends-on ("_package_DigitalSensor"))
    (:file "_package_DigitalSensor" :depends-on ("_package"))
    (:file "EncoderDifferential" :depends-on ("_package_EncoderDifferential"))
    (:file "_package_EncoderDifferential" :depends-on ("_package"))
    (:file "ErrorRobotToPath" :depends-on ("_package_ErrorRobotToPath"))
    (:file "_package_ErrorRobotToPath" :depends-on ("_package"))
    (:file "FollowLineControl" :depends-on ("_package_FollowLineControl"))
    (:file "_package_FollowLineControl" :depends-on ("_package"))
    (:file "FollowLineSensor" :depends-on ("_package_FollowLineSensor"))
    (:file "_package_FollowLineSensor" :depends-on ("_package"))
    (:file "HmiControl" :depends-on ("_package_HmiControl"))
    (:file "_package_HmiControl" :depends-on ("_package"))
    (:file "LedControl" :depends-on ("_package_LedControl"))
    (:file "_package_LedControl" :depends-on ("_package"))
    (:file "Pid" :depends-on ("_package_Pid"))
    (:file "_package_Pid" :depends-on ("_package"))
    (:file "SafetyControl" :depends-on ("_package_SafetyControl"))
    (:file "_package_SafetyControl" :depends-on ("_package"))
    (:file "SafetyStt" :depends-on ("_package_SafetyStt"))
    (:file "_package_SafetyStt" :depends-on ("_package"))
    (:file "WaypointGlobal" :depends-on ("_package_WaypointGlobal"))
    (:file "_package_WaypointGlobal" :depends-on ("_package"))
  ))