// Generated by gencpp from file agv_msgs/ArduinoIO.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_ARDUINOIO_H
#define AGV_MSGS_MESSAGE_ARDUINOIO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct ArduinoIO_
{
  typedef ArduinoIO_<ContainerAllocator> Type;

  ArduinoIO_()
    : header()
    , EMG(false)
    , Start_1(false)
    , Start_2(false)
    , Stop_1(false)
    , Stop_2(false)
    , Remote_A(false)
    , Remote_B(false)
    , Motor1_En(false)
    , Motor1_Break(false)
    , Motor1_Dir(false)
    , Motor2_En(false)
    , Motor2_Break(false)
    , Motor2_Dir(false)
    , Bumper_1(false)
    , Bumper_2(false)
    , lift_max(false)
    , lift_min(false)
    , auto_man_sw(false)
    , Release_motor(false)
    , Battery_1(0.0)
    , Battery_2(0.0)
    , Battery_3(0.0)
    , Battery_4(0.0)
    , Charging(false)
    , Encoder_Left(0)
    , Encoder_Right(0)
    , Safety_1(0)
    , Safety_2(0)
    , Safety_3(0)
    , Safety_4(0)  {
    }
  ArduinoIO_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , EMG(false)
    , Start_1(false)
    , Start_2(false)
    , Stop_1(false)
    , Stop_2(false)
    , Remote_A(false)
    , Remote_B(false)
    , Motor1_En(false)
    , Motor1_Break(false)
    , Motor1_Dir(false)
    , Motor2_En(false)
    , Motor2_Break(false)
    , Motor2_Dir(false)
    , Bumper_1(false)
    , Bumper_2(false)
    , lift_max(false)
    , lift_min(false)
    , auto_man_sw(false)
    , Release_motor(false)
    , Battery_1(0.0)
    , Battery_2(0.0)
    , Battery_3(0.0)
    , Battery_4(0.0)
    , Charging(false)
    , Encoder_Left(0)
    , Encoder_Right(0)
    , Safety_1(0)
    , Safety_2(0)
    , Safety_3(0)
    , Safety_4(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _EMG_type;
  _EMG_type EMG;

   typedef uint8_t _Start_1_type;
  _Start_1_type Start_1;

   typedef uint8_t _Start_2_type;
  _Start_2_type Start_2;

   typedef uint8_t _Stop_1_type;
  _Stop_1_type Stop_1;

   typedef uint8_t _Stop_2_type;
  _Stop_2_type Stop_2;

   typedef uint8_t _Remote_A_type;
  _Remote_A_type Remote_A;

   typedef uint8_t _Remote_B_type;
  _Remote_B_type Remote_B;

   typedef uint8_t _Motor1_En_type;
  _Motor1_En_type Motor1_En;

   typedef uint8_t _Motor1_Break_type;
  _Motor1_Break_type Motor1_Break;

   typedef uint8_t _Motor1_Dir_type;
  _Motor1_Dir_type Motor1_Dir;

   typedef uint8_t _Motor2_En_type;
  _Motor2_En_type Motor2_En;

   typedef uint8_t _Motor2_Break_type;
  _Motor2_Break_type Motor2_Break;

   typedef uint8_t _Motor2_Dir_type;
  _Motor2_Dir_type Motor2_Dir;

   typedef uint8_t _Bumper_1_type;
  _Bumper_1_type Bumper_1;

   typedef uint8_t _Bumper_2_type;
  _Bumper_2_type Bumper_2;

   typedef uint8_t _lift_max_type;
  _lift_max_type lift_max;

   typedef uint8_t _lift_min_type;
  _lift_min_type lift_min;

   typedef uint8_t _auto_man_sw_type;
  _auto_man_sw_type auto_man_sw;

   typedef uint8_t _Release_motor_type;
  _Release_motor_type Release_motor;

   typedef float _Battery_1_type;
  _Battery_1_type Battery_1;

   typedef float _Battery_2_type;
  _Battery_2_type Battery_2;

   typedef float _Battery_3_type;
  _Battery_3_type Battery_3;

   typedef float _Battery_4_type;
  _Battery_4_type Battery_4;

   typedef uint8_t _Charging_type;
  _Charging_type Charging;

   typedef int32_t _Encoder_Left_type;
  _Encoder_Left_type Encoder_Left;

   typedef int32_t _Encoder_Right_type;
  _Encoder_Right_type Encoder_Right;

   typedef uint16_t _Safety_1_type;
  _Safety_1_type Safety_1;

   typedef uint16_t _Safety_2_type;
  _Safety_2_type Safety_2;

   typedef uint16_t _Safety_3_type;
  _Safety_3_type Safety_3;

   typedef uint16_t _Safety_4_type;
  _Safety_4_type Safety_4;





  typedef boost::shared_ptr< ::agv_msgs::ArduinoIO_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::ArduinoIO_<ContainerAllocator> const> ConstPtr;

}; // struct ArduinoIO_

typedef ::agv_msgs::ArduinoIO_<std::allocator<void> > ArduinoIO;

typedef boost::shared_ptr< ::agv_msgs::ArduinoIO > ArduinoIOPtr;
typedef boost::shared_ptr< ::agv_msgs::ArduinoIO const> ArduinoIOConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::ArduinoIO_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::ArduinoIO_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::ArduinoIO_<ContainerAllocator1> & lhs, const ::agv_msgs::ArduinoIO_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.EMG == rhs.EMG &&
    lhs.Start_1 == rhs.Start_1 &&
    lhs.Start_2 == rhs.Start_2 &&
    lhs.Stop_1 == rhs.Stop_1 &&
    lhs.Stop_2 == rhs.Stop_2 &&
    lhs.Remote_A == rhs.Remote_A &&
    lhs.Remote_B == rhs.Remote_B &&
    lhs.Motor1_En == rhs.Motor1_En &&
    lhs.Motor1_Break == rhs.Motor1_Break &&
    lhs.Motor1_Dir == rhs.Motor1_Dir &&
    lhs.Motor2_En == rhs.Motor2_En &&
    lhs.Motor2_Break == rhs.Motor2_Break &&
    lhs.Motor2_Dir == rhs.Motor2_Dir &&
    lhs.Bumper_1 == rhs.Bumper_1 &&
    lhs.Bumper_2 == rhs.Bumper_2 &&
    lhs.lift_max == rhs.lift_max &&
    lhs.lift_min == rhs.lift_min &&
    lhs.auto_man_sw == rhs.auto_man_sw &&
    lhs.Release_motor == rhs.Release_motor &&
    lhs.Battery_1 == rhs.Battery_1 &&
    lhs.Battery_2 == rhs.Battery_2 &&
    lhs.Battery_3 == rhs.Battery_3 &&
    lhs.Battery_4 == rhs.Battery_4 &&
    lhs.Charging == rhs.Charging &&
    lhs.Encoder_Left == rhs.Encoder_Left &&
    lhs.Encoder_Right == rhs.Encoder_Right &&
    lhs.Safety_1 == rhs.Safety_1 &&
    lhs.Safety_2 == rhs.Safety_2 &&
    lhs.Safety_3 == rhs.Safety_3 &&
    lhs.Safety_4 == rhs.Safety_4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::ArduinoIO_<ContainerAllocator1> & lhs, const ::agv_msgs::ArduinoIO_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::ArduinoIO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::ArduinoIO_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::ArduinoIO_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::ArduinoIO_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::ArduinoIO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::ArduinoIO_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::ArduinoIO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "675bff81b91834773820b3bad7d42153";
  }

  static const char* value(const ::agv_msgs::ArduinoIO_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x675bff81b9183477ULL;
  static const uint64_t static_value2 = 0x3820b3bad7d42153ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::ArduinoIO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/ArduinoIO";
  }

  static const char* value(const ::agv_msgs::ArduinoIO_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::ArduinoIO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"bool EMG\n"
"bool Start_1\n"
"bool Start_2\n"
"bool Stop_1\n"
"bool Stop_2\n"
"bool Remote_A\n"
"bool Remote_B\n"
"bool Motor1_En\n"
"bool Motor1_Break\n"
"bool Motor1_Dir\n"
"bool Motor2_En\n"
"bool Motor2_Break\n"
"bool Motor2_Dir\n"
"bool Bumper_1\n"
"bool Bumper_2\n"
"bool lift_max\n"
"bool lift_min\n"
"bool auto_man_sw\n"
"bool Release_motor\n"
"float32 Battery_1\n"
"float32 Battery_2\n"
"float32 Battery_3\n"
"float32 Battery_4\n"
"bool Charging\n"
"int32 Encoder_Left\n"
"int32 Encoder_Right\n"
"uint16 Safety_1\n"
"uint16 Safety_2\n"
"uint16 Safety_3\n"
"uint16 Safety_4\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::agv_msgs::ArduinoIO_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::ArduinoIO_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.EMG);
      stream.next(m.Start_1);
      stream.next(m.Start_2);
      stream.next(m.Stop_1);
      stream.next(m.Stop_2);
      stream.next(m.Remote_A);
      stream.next(m.Remote_B);
      stream.next(m.Motor1_En);
      stream.next(m.Motor1_Break);
      stream.next(m.Motor1_Dir);
      stream.next(m.Motor2_En);
      stream.next(m.Motor2_Break);
      stream.next(m.Motor2_Dir);
      stream.next(m.Bumper_1);
      stream.next(m.Bumper_2);
      stream.next(m.lift_max);
      stream.next(m.lift_min);
      stream.next(m.auto_man_sw);
      stream.next(m.Release_motor);
      stream.next(m.Battery_1);
      stream.next(m.Battery_2);
      stream.next(m.Battery_3);
      stream.next(m.Battery_4);
      stream.next(m.Charging);
      stream.next(m.Encoder_Left);
      stream.next(m.Encoder_Right);
      stream.next(m.Safety_1);
      stream.next(m.Safety_2);
      stream.next(m.Safety_3);
      stream.next(m.Safety_4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArduinoIO_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::ArduinoIO_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::ArduinoIO_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "EMG: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.EMG);
    s << indent << "Start_1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Start_1);
    s << indent << "Start_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Start_2);
    s << indent << "Stop_1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Stop_1);
    s << indent << "Stop_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Stop_2);
    s << indent << "Remote_A: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Remote_A);
    s << indent << "Remote_B: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Remote_B);
    s << indent << "Motor1_En: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor1_En);
    s << indent << "Motor1_Break: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor1_Break);
    s << indent << "Motor1_Dir: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor1_Dir);
    s << indent << "Motor2_En: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor2_En);
    s << indent << "Motor2_Break: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor2_Break);
    s << indent << "Motor2_Dir: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor2_Dir);
    s << indent << "Bumper_1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Bumper_1);
    s << indent << "Bumper_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Bumper_2);
    s << indent << "lift_max: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lift_max);
    s << indent << "lift_min: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lift_min);
    s << indent << "auto_man_sw: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_man_sw);
    s << indent << "Release_motor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Release_motor);
    s << indent << "Battery_1: ";
    Printer<float>::stream(s, indent + "  ", v.Battery_1);
    s << indent << "Battery_2: ";
    Printer<float>::stream(s, indent + "  ", v.Battery_2);
    s << indent << "Battery_3: ";
    Printer<float>::stream(s, indent + "  ", v.Battery_3);
    s << indent << "Battery_4: ";
    Printer<float>::stream(s, indent + "  ", v.Battery_4);
    s << indent << "Charging: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Charging);
    s << indent << "Encoder_Left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Encoder_Left);
    s << indent << "Encoder_Right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Encoder_Right);
    s << indent << "Safety_1: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Safety_1);
    s << indent << "Safety_2: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Safety_2);
    s << indent << "Safety_3: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Safety_3);
    s << indent << "Safety_4: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Safety_4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_ARDUINOIO_H
