// Generated by gencpp from file agv_msgs/ArrayWaypointsResponse.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_ARRAYWAYPOINTSRESPONSE_H
#define AGV_MSGS_MESSAGE_ARRAYWAYPOINTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace agv_msgs
{
template <class ContainerAllocator>
struct ArrayWaypointsResponse_
{
  typedef ArrayWaypointsResponse_<ContainerAllocator> Type;

  ArrayWaypointsResponse_()
    : Waypoints()  {
    }
  ArrayWaypointsResponse_(const ContainerAllocator& _alloc)
    : Waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PoseStamped_<ContainerAllocator> >> _Waypoints_type;
  _Waypoints_type Waypoints;





  typedef boost::shared_ptr< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ArrayWaypointsResponse_

typedef ::agv_msgs::ArrayWaypointsResponse_<std::allocator<void> > ArrayWaypointsResponse;

typedef boost::shared_ptr< ::agv_msgs::ArrayWaypointsResponse > ArrayWaypointsResponsePtr;
typedef boost::shared_ptr< ::agv_msgs::ArrayWaypointsResponse const> ArrayWaypointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator1> & lhs, const ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Waypoints == rhs.Waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator1> & lhs, const ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7a462d7837fb67629ef9c43385f3fb8";
  }

  static const char* value(const ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7a462d7837fb676ULL;
  static const uint64_t static_value2 = 0x29ef9c43385f3fb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/ArrayWaypointsResponse";
  }

  static const char* value(const ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped[] Waypoints\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArrayWaypointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::ArrayWaypointsResponse_<ContainerAllocator>& v)
  {
    s << indent << "Waypoints[]" << std::endl;
    for (size_t i = 0; i < v.Waypoints.size(); ++i)
    {
      s << indent << "  Waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.Waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_ARRAYWAYPOINTSRESPONSE_H
