// Generated by gencpp from file agv_msgs/BasicFunction.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_BASICFUNCTION_H
#define AGV_MSGS_MESSAGE_BASICFUNCTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct BasicFunction_
{
  typedef BasicFunction_<ContainerAllocator> Type;

  BasicFunction_()
    : FuncId(0)
    , ParId(0)  {
    }
  BasicFunction_(const ContainerAllocator& _alloc)
    : FuncId(0)
    , ParId(0)  {
  (void)_alloc;
    }



   typedef int8_t _FuncId_type;
  _FuncId_type FuncId;

   typedef int8_t _ParId_type;
  _ParId_type ParId;





  typedef boost::shared_ptr< ::agv_msgs::BasicFunction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::BasicFunction_<ContainerAllocator> const> ConstPtr;

}; // struct BasicFunction_

typedef ::agv_msgs::BasicFunction_<std::allocator<void> > BasicFunction;

typedef boost::shared_ptr< ::agv_msgs::BasicFunction > BasicFunctionPtr;
typedef boost::shared_ptr< ::agv_msgs::BasicFunction const> BasicFunctionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::BasicFunction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::BasicFunction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::BasicFunction_<ContainerAllocator1> & lhs, const ::agv_msgs::BasicFunction_<ContainerAllocator2> & rhs)
{
  return lhs.FuncId == rhs.FuncId &&
    lhs.ParId == rhs.ParId;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::BasicFunction_<ContainerAllocator1> & lhs, const ::agv_msgs::BasicFunction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::BasicFunction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::BasicFunction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::BasicFunction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::BasicFunction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::BasicFunction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::BasicFunction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::BasicFunction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bd1e71c4c1a7cc1e9127efa7dba7022";
  }

  static const char* value(const ::agv_msgs::BasicFunction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bd1e71c4c1a7cc1ULL;
  static const uint64_t static_value2 = 0xe9127efa7dba7022ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::BasicFunction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/BasicFunction";
  }

  static const char* value(const ::agv_msgs::BasicFunction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::BasicFunction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 FuncId\n"
"int8 ParId\n"
;
  }

  static const char* value(const ::agv_msgs::BasicFunction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::BasicFunction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FuncId);
      stream.next(m.ParId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BasicFunction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::BasicFunction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::BasicFunction_<ContainerAllocator>& v)
  {
    s << indent << "FuncId: ";
    Printer<int8_t>::stream(s, indent + "  ", v.FuncId);
    s << indent << "ParId: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ParId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_BASICFUNCTION_H
