// Generated by gencpp from file agv_msgs/DataCheckResponse.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_DATACHECKRESPONSE_H
#define AGV_MSGS_MESSAGE_DATACHECKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct DataCheckResponse_
{
  typedef DataCheckResponse_<ContainerAllocator> Type;

  DataCheckResponse_()
    : Res()  {
    }
  DataCheckResponse_(const ContainerAllocator& _alloc)
    : Res(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Res_type;
  _Res_type Res;





  typedef boost::shared_ptr< ::agv_msgs::DataCheckResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::DataCheckResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DataCheckResponse_

typedef ::agv_msgs::DataCheckResponse_<std::allocator<void> > DataCheckResponse;

typedef boost::shared_ptr< ::agv_msgs::DataCheckResponse > DataCheckResponsePtr;
typedef boost::shared_ptr< ::agv_msgs::DataCheckResponse const> DataCheckResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::DataCheckResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::DataCheckResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::DataCheckResponse_<ContainerAllocator1> & lhs, const ::agv_msgs::DataCheckResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Res == rhs.Res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::DataCheckResponse_<ContainerAllocator1> & lhs, const ::agv_msgs::DataCheckResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::DataCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::DataCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::DataCheckResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::DataCheckResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::DataCheckResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::DataCheckResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::DataCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adc762752bc2aac9031068139943f509";
  }

  static const char* value(const ::agv_msgs::DataCheckResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xadc762752bc2aac9ULL;
  static const uint64_t static_value2 = 0x031068139943f509ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::DataCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/DataCheckResponse";
  }

  static const char* value(const ::agv_msgs::DataCheckResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::DataCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Res\n"
;
  }

  static const char* value(const ::agv_msgs::DataCheckResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::DataCheckResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataCheckResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::DataCheckResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::DataCheckResponse_<ContainerAllocator>& v)
  {
    s << indent << "Res: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_DATACHECKRESPONSE_H
