// Generated by gencpp from file agv_msgs/DiffDriverMotorSpeed.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_DIFFDRIVERMOTORSPEED_H
#define AGV_MSGS_MESSAGE_DIFFDRIVERMOTORSPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct DiffDriverMotorSpeed_
{
  typedef DiffDriverMotorSpeed_<ContainerAllocator> Type;

  DiffDriverMotorSpeed_()
    : Direction(false)
    , BaseSpeed(0)
    , Left(0.0)
    , Right(0.0)
    , Break(false)  {
    }
  DiffDriverMotorSpeed_(const ContainerAllocator& _alloc)
    : Direction(false)
    , BaseSpeed(0)
    , Left(0.0)
    , Right(0.0)
    , Break(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Direction_type;
  _Direction_type Direction;

   typedef int16_t _BaseSpeed_type;
  _BaseSpeed_type BaseSpeed;

   typedef float _Left_type;
  _Left_type Left;

   typedef float _Right_type;
  _Right_type Right;

   typedef uint8_t _Break_type;
  _Break_type Break;





  typedef boost::shared_ptr< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct DiffDriverMotorSpeed_

typedef ::agv_msgs::DiffDriverMotorSpeed_<std::allocator<void> > DiffDriverMotorSpeed;

typedef boost::shared_ptr< ::agv_msgs::DiffDriverMotorSpeed > DiffDriverMotorSpeedPtr;
typedef boost::shared_ptr< ::agv_msgs::DiffDriverMotorSpeed const> DiffDriverMotorSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator1> & lhs, const ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.Direction == rhs.Direction &&
    lhs.BaseSpeed == rhs.BaseSpeed &&
    lhs.Left == rhs.Left &&
    lhs.Right == rhs.Right &&
    lhs.Break == rhs.Break;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator1> & lhs, const ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd5fbb3f71154e3a8fc658dbedadf9d6";
  }

  static const char* value(const ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd5fbb3f71154e3aULL;
  static const uint64_t static_value2 = 0x8fc658dbedadf9d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/DiffDriverMotorSpeed";
  }

  static const char* value(const ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Direction # Forward = 0, Backward = 1\n"
"int16 BaseSpeed # 0 -> 255\n"
"float32 Left # 0 -> 100\n"
"float32 Right # 0 -> 100\n"
"bool Break\n"
;
  }

  static const char* value(const ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Direction);
      stream.next(m.BaseSpeed);
      stream.next(m.Left);
      stream.next(m.Right);
      stream.next(m.Break);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DiffDriverMotorSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::DiffDriverMotorSpeed_<ContainerAllocator>& v)
  {
    s << indent << "Direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Direction);
    s << indent << "BaseSpeed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.BaseSpeed);
    s << indent << "Left: ";
    Printer<float>::stream(s, indent + "  ", v.Left);
    s << indent << "Right: ";
    Printer<float>::stream(s, indent + "  ", v.Right);
    s << indent << "Break: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Break);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_DIFFDRIVERMOTORSPEED_H
