// Generated by gencpp from file agv_msgs/DirectionMoveResponse.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_DIRECTIONMOVERESPONSE_H
#define AGV_MSGS_MESSAGE_DIRECTIONMOVERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct DirectionMoveResponse_
{
  typedef DirectionMoveResponse_<ContainerAllocator> Type;

  DirectionMoveResponse_()
    : direction(0)  {
    }
  DirectionMoveResponse_(const ContainerAllocator& _alloc)
    : direction(0)  {
  (void)_alloc;
    }



   typedef int8_t _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DirectionMoveResponse_

typedef ::agv_msgs::DirectionMoveResponse_<std::allocator<void> > DirectionMoveResponse;

typedef boost::shared_ptr< ::agv_msgs::DirectionMoveResponse > DirectionMoveResponsePtr;
typedef boost::shared_ptr< ::agv_msgs::DirectionMoveResponse const> DirectionMoveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::DirectionMoveResponse_<ContainerAllocator1> & lhs, const ::agv_msgs::DirectionMoveResponse_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::DirectionMoveResponse_<ContainerAllocator1> & lhs, const ::agv_msgs::DirectionMoveResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82056227860a27ca2b5bdb9859d50460";
  }

  static const char* value(const ::agv_msgs::DirectionMoveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82056227860a27caULL;
  static const uint64_t static_value2 = 0x2b5bdb9859d50460ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/DirectionMoveResponse";
  }

  static const char* value(const ::agv_msgs::DirectionMoveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 direction # 0: free, 1:forward, 2: backward\n"
;
  }

  static const char* value(const ::agv_msgs::DirectionMoveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DirectionMoveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::DirectionMoveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::DirectionMoveResponse_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<int8_t>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_DIRECTIONMOVERESPONSE_H
