// Generated by gencpp from file agv_msgs/ErrorRobotToPath.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_ERRORROBOTTOPATH_H
#define AGV_MSGS_MESSAGE_ERRORROBOTTOPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct ErrorRobotToPath_
{
  typedef ErrorRobotToPath_<ContainerAllocator> Type;

  ErrorRobotToPath_()
    : error_angle(0.0)
    , error_position(0.0)  {
    }
  ErrorRobotToPath_(const ContainerAllocator& _alloc)
    : error_angle(0.0)
    , error_position(0.0)  {
  (void)_alloc;
    }



   typedef double _error_angle_type;
  _error_angle_type error_angle;

   typedef double _error_position_type;
  _error_position_type error_position;





  typedef boost::shared_ptr< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> const> ConstPtr;

}; // struct ErrorRobotToPath_

typedef ::agv_msgs::ErrorRobotToPath_<std::allocator<void> > ErrorRobotToPath;

typedef boost::shared_ptr< ::agv_msgs::ErrorRobotToPath > ErrorRobotToPathPtr;
typedef boost::shared_ptr< ::agv_msgs::ErrorRobotToPath const> ErrorRobotToPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::ErrorRobotToPath_<ContainerAllocator1> & lhs, const ::agv_msgs::ErrorRobotToPath_<ContainerAllocator2> & rhs)
{
  return lhs.error_angle == rhs.error_angle &&
    lhs.error_position == rhs.error_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::ErrorRobotToPath_<ContainerAllocator1> & lhs, const ::agv_msgs::ErrorRobotToPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfe8fe7d4e33da3bdbaadca9414e0299";
  }

  static const char* value(const ::agv_msgs::ErrorRobotToPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdfe8fe7d4e33da3bULL;
  static const uint64_t static_value2 = 0xdbaadca9414e0299ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/ErrorRobotToPath";
  }

  static const char* value(const ::agv_msgs::ErrorRobotToPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 error_angle\n"
"float64 error_position\n"
;
  }

  static const char* value(const ::agv_msgs::ErrorRobotToPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_angle);
      stream.next(m.error_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ErrorRobotToPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::ErrorRobotToPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::ErrorRobotToPath_<ContainerAllocator>& v)
  {
    s << indent << "error_angle: ";
    Printer<double>::stream(s, indent + "  ", v.error_angle);
    s << indent << "error_position: ";
    Printer<double>::stream(s, indent + "  ", v.error_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_ERRORROBOTTOPATH_H
