// Generated by gencpp from file agv_msgs/SafetyStt.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_SAFETYSTT_H
#define AGV_MSGS_MESSAGE_SAFETYSTT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct SafetyStt_
{
  typedef SafetyStt_<ContainerAllocator> Type;

  SafetyStt_()
    : Id(0)
    , Name()
    , Current_Job(0)
    , Range_1(0)
    , Range_2(0)
    , Range_3(0)  {
    }
  SafetyStt_(const ContainerAllocator& _alloc)
    : Id(0)
    , Name(_alloc)
    , Current_Job(0)
    , Range_1(0)
    , Range_2(0)
    , Range_3(0)  {
  (void)_alloc;
    }



   typedef uint8_t _Id_type;
  _Id_type Id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Name_type;
  _Name_type Name;

   typedef uint8_t _Current_Job_type;
  _Current_Job_type Current_Job;

   typedef uint8_t _Range_1_type;
  _Range_1_type Range_1;

   typedef uint8_t _Range_2_type;
  _Range_2_type Range_2;

   typedef uint8_t _Range_3_type;
  _Range_3_type Range_3;





  typedef boost::shared_ptr< ::agv_msgs::SafetyStt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::SafetyStt_<ContainerAllocator> const> ConstPtr;

}; // struct SafetyStt_

typedef ::agv_msgs::SafetyStt_<std::allocator<void> > SafetyStt;

typedef boost::shared_ptr< ::agv_msgs::SafetyStt > SafetySttPtr;
typedef boost::shared_ptr< ::agv_msgs::SafetyStt const> SafetySttConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::SafetyStt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::SafetyStt_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::SafetyStt_<ContainerAllocator1> & lhs, const ::agv_msgs::SafetyStt_<ContainerAllocator2> & rhs)
{
  return lhs.Id == rhs.Id &&
    lhs.Name == rhs.Name &&
    lhs.Current_Job == rhs.Current_Job &&
    lhs.Range_1 == rhs.Range_1 &&
    lhs.Range_2 == rhs.Range_2 &&
    lhs.Range_3 == rhs.Range_3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::SafetyStt_<ContainerAllocator1> & lhs, const ::agv_msgs::SafetyStt_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::SafetyStt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::SafetyStt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::SafetyStt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::SafetyStt_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::SafetyStt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::SafetyStt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::SafetyStt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f93827b3264a5c1f06a6cdd2faf3051e";
  }

  static const char* value(const ::agv_msgs::SafetyStt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf93827b3264a5c1fULL;
  static const uint64_t static_value2 = 0x06a6cdd2faf3051eULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::SafetyStt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/SafetyStt";
  }

  static const char* value(const ::agv_msgs::SafetyStt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::SafetyStt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 Id\n"
"string Name\n"
"uint8 Current_Job\n"
"uint8 Range_1\n"
"uint8 Range_2\n"
"uint8 Range_3\n"
;
  }

  static const char* value(const ::agv_msgs::SafetyStt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::SafetyStt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Id);
      stream.next(m.Name);
      stream.next(m.Current_Job);
      stream.next(m.Range_1);
      stream.next(m.Range_2);
      stream.next(m.Range_3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SafetyStt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::SafetyStt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::SafetyStt_<ContainerAllocator>& v)
  {
    s << indent << "Id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Id);
    s << indent << "Name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Name);
    s << indent << "Current_Job: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Current_Job);
    s << indent << "Range_1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Range_1);
    s << indent << "Range_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Range_2);
    s << indent << "Range_3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Range_3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_SAFETYSTT_H
