// Generated by gencpp from file agv_msgs/SetDigitalOutputRequest.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_SETDIGITALOUTPUTREQUEST_H
#define AGV_MSGS_MESSAGE_SETDIGITALOUTPUTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct SetDigitalOutputRequest_
{
  typedef SetDigitalOutputRequest_<ContainerAllocator> Type;

  SetDigitalOutputRequest_()
    : pin(0)
    , value(false)
    , duration_latch_ms(0)
    , duration_blink_ms(0)  {
    }
  SetDigitalOutputRequest_(const ContainerAllocator& _alloc)
    : pin(0)
    , value(false)
    , duration_latch_ms(0)
    , duration_blink_ms(0)  {
  (void)_alloc;
    }



   typedef int8_t _pin_type;
  _pin_type pin;

   typedef uint8_t _value_type;
  _value_type value;

   typedef int64_t _duration_latch_ms_type;
  _duration_latch_ms_type duration_latch_ms;

   typedef int64_t _duration_blink_ms_type;
  _duration_blink_ms_type duration_blink_ms;





  typedef boost::shared_ptr< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDigitalOutputRequest_

typedef ::agv_msgs::SetDigitalOutputRequest_<std::allocator<void> > SetDigitalOutputRequest;

typedef boost::shared_ptr< ::agv_msgs::SetDigitalOutputRequest > SetDigitalOutputRequestPtr;
typedef boost::shared_ptr< ::agv_msgs::SetDigitalOutputRequest const> SetDigitalOutputRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator1> & lhs, const ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pin == rhs.pin &&
    lhs.value == rhs.value &&
    lhs.duration_latch_ms == rhs.duration_latch_ms &&
    lhs.duration_blink_ms == rhs.duration_blink_ms;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator1> & lhs, const ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb44bbbb2d68dd58810edaa5d98aa5a1";
  }

  static const char* value(const ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb44bbbb2d68dd58ULL;
  static const uint64_t static_value2 = 0x810edaa5d98aa5a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/SetDigitalOutputRequest";
  }

  static const char* value(const ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 pin\n"
"bool value\n"
"# If duration_latch > 0 and duration_blink = 0, the output latch n (ms) then\n"
"# set to set the opposite value (True to False and False to True)\n"
"int64 duration_latch_ms\n"
"# If duration_blink > 0 and duration_latch = 0, the output toggle with\n"
"# duration = duration_latch (ms)\n"
"int64 duration_blink_ms\n"
;
  }

  static const char* value(const ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pin);
      stream.next(m.value);
      stream.next(m.duration_latch_ms);
      stream.next(m.duration_blink_ms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDigitalOutputRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_msgs::SetDigitalOutputRequest_<ContainerAllocator>& v)
  {
    s << indent << "pin: ";
    Printer<int8_t>::stream(s, indent + "  ", v.pin);
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
    s << indent << "duration_latch_ms: ";
    Printer<int64_t>::stream(s, indent + "  ", v.duration_latch_ms);
    s << indent << "duration_blink_ms: ";
    Printer<int64_t>::stream(s, indent + "  ", v.duration_blink_ms);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_SETDIGITALOUTPUTREQUEST_H
