// Generated by gencpp from file agv_msgs/WaypointsPathRequest.msg
// DO NOT EDIT!


#ifndef AGV_MSGS_MESSAGE_WAYPOINTSPATHREQUEST_H
#define AGV_MSGS_MESSAGE_WAYPOINTSPATHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_msgs
{
template <class ContainerAllocator>
struct WaypointsPathRequest_
{
  typedef WaypointsPathRequest_<ContainerAllocator> Type;

  WaypointsPathRequest_()
    {
    }
  WaypointsPathRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointsPathRequest_

typedef ::agv_msgs::WaypointsPathRequest_<std::allocator<void> > WaypointsPathRequest;

typedef boost::shared_ptr< ::agv_msgs::WaypointsPathRequest > WaypointsPathRequestPtr;
typedef boost::shared_ptr< ::agv_msgs::WaypointsPathRequest const> WaypointsPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace agv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::agv_msgs::WaypointsPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_msgs/WaypointsPathRequest";
  }

  static const char* value(const ::agv_msgs::WaypointsPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::agv_msgs::WaypointsPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointsPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_msgs::WaypointsPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::agv_msgs::WaypointsPathRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MSGS_MESSAGE_WAYPOINTSPATHREQUEST_H
