mirror:
  use_mirror: false
mapping:
  # method: gmapping
  # launch_file: roslaunch agvlidar_navigation gmapping.launch
  # ros_node:
  #   - /gmapping # Main node always in top
  #   - /get_marker
  # map_save_cmd: rosrun map_server map_saver -f
  method: cartographer
  launch_file: roslaunch cartographer_run slam.launch
  ros_node: # Main node always in top
    - /cartographer_occupancy_grid_slam
    - /cartographer_node_slam
    # - /get_marker
  map_save_cmd: rosrun cartographer_run save_map.py # Create launch file has --map_file
  load_map_timeout: 30 # Seconds

localization:
  # method: map_server_amcl
  # launch_file: roslaunch agvlidar_navigation map_server_amcl.launch

  # ros_node:
  #   - /map_server # Map source node (/map_server) always in top
  #   - /amcl
  #   - /cartographer_node_localization # When swing map_server_amcl to cartographer
  #   # - /locate_marker
  # map_file_ext: yaml
  # image_file_input: png
  # # map_file_param: map_server don't has this param
  # # convert_map_cmd: png_to_pgm.sh
  # convert_map_cmd: rosrun slam_manager convert_to_gray.sh
  # load_map_timeout: 30 # Seconds

  # method: mrpt
  # launch_file: roslaunch agvlidar_navigation mrpt.launch
  # ros_node:
  #   - /mrpt_localization_node # Map source node (/mrpt) always in top
  #   - /locate_marker
  # image_file_input: png
  # gen_map: rosrun slam_manager make_mrpt_map.sh
  # map_file_ext: gridmap

  # download_image_map: true
  # map_file_param: /mrpt_localization_node/map_file
  # convert_map_cmd: rosrun slam_manager make_mrpt_map.sh

  method: cartographer
  launch_file: roslaunch cartographer_run localization.launch
  launch_static_map: roslaunch cartographer_run fix_map.launch
  static_map_node:
    - /cartographer_occupancy_grid_static
    - /cartographer_node_static_map
  ros_node:
    - /map_server # Map source node (/map_server) always in top
    - /cartographer_occupancy_grid_localization
    - /cartographer_node_localization
    - /amcl # When swing map_server_amcl to cartographer
    # - /locate_marker
  image_file_input: png
  map_file_ext: pbstream

  download_image_map: true
  convert_map_cmd: rosrun slam_manager convert_to_gray.sh
  load_map_timeout: 30 # Seconds
