; Auto-generated. Do not edit!


(cl:in-package mission_manager-msg)


;//! \htmlinclude CheckPositionStatusFeedback.msg.html

(cl:defclass <CheckPositionStatusFeedback> (roslisp-msg-protocol:ros-message)
  ((rest_time
    :reader rest_time
    :initarg :rest_time
    :type cl:float
    :initform 0.0))
)

(cl:defclass CheckPositionStatusFeedback (<CheckPositionStatusFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CheckPositionStatusFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CheckPositionStatusFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mission_manager-msg:<CheckPositionStatusFeedback> is deprecated: use mission_manager-msg:CheckPositionStatusFeedback instead.")))

(cl:ensure-generic-function 'rest_time-val :lambda-list '(m))
(cl:defmethod rest_time-val ((m <CheckPositionStatusFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mission_manager-msg:rest_time-val is deprecated.  Use mission_manager-msg:rest_time instead.")
  (rest_time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CheckPositionStatusFeedback>) ostream)
  "Serializes a message object of type '<CheckPositionStatusFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'rest_time))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CheckPositionStatusFeedback>) istream)
  "Deserializes a message object of type '<CheckPositionStatusFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'rest_time) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CheckPositionStatusFeedback>)))
  "Returns string type for a message object of type '<CheckPositionStatusFeedback>"
  "mission_manager/CheckPositionStatusFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CheckPositionStatusFeedback)))
  "Returns string type for a message object of type 'CheckPositionStatusFeedback"
  "mission_manager/CheckPositionStatusFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CheckPositionStatusFeedback>)))
  "Returns md5sum for a message object of type '<CheckPositionStatusFeedback>"
  "80e5059cedd56925a543afc9b5aadef4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CheckPositionStatusFeedback)))
  "Returns md5sum for a message object of type 'CheckPositionStatusFeedback"
  "80e5059cedd56925a543afc9b5aadef4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CheckPositionStatusFeedback>)))
  "Returns full string definition for message of type '<CheckPositionStatusFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 rest_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CheckPositionStatusFeedback)))
  "Returns full string definition for message of type 'CheckPositionStatusFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 rest_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CheckPositionStatusFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CheckPositionStatusFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CheckPositionStatusFeedback
    (cl:cons ':rest_time (rest_time msg))
))
