// Generated by gencpp from file fastech_io/GetIO.msg
// DO NOT EDIT!


#ifndef FASTECH_IO_MESSAGE_GETIO_H
#define FASTECH_IO_MESSAGE_GETIO_H

#include <ros/service_traits.h>


#include <fastech_io/GetIORequest.h>
#include <fastech_io/GetIOResponse.h>


namespace fastech_io
{

struct GetIO
{

typedef GetIORequest Request;
typedef GetIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetIO
} // namespace fastech_io


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fastech_io::GetIO > {
  static const char* value()
  {
    return "8dc7716b39efd26155b31938acfbd81d";
  }

  static const char* value(const ::fastech_io::GetIO&) { return value(); }
};

template<>
struct DataType< ::fastech_io::GetIO > {
  static const char* value()
  {
    return "fastech_io/GetIO";
  }

  static const char* value(const ::fastech_io::GetIO&) { return value(); }
};


// service_traits::MD5Sum< ::fastech_io::GetIORequest> should match
// service_traits::MD5Sum< ::fastech_io::GetIO >
template<>
struct MD5Sum< ::fastech_io::GetIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::fastech_io::GetIO >::value();
  }
  static const char* value(const ::fastech_io::GetIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastech_io::GetIORequest> should match
// service_traits::DataType< ::fastech_io::GetIO >
template<>
struct DataType< ::fastech_io::GetIORequest>
{
  static const char* value()
  {
    return DataType< ::fastech_io::GetIO >::value();
  }
  static const char* value(const ::fastech_io::GetIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fastech_io::GetIOResponse> should match
// service_traits::MD5Sum< ::fastech_io::GetIO >
template<>
struct MD5Sum< ::fastech_io::GetIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fastech_io::GetIO >::value();
  }
  static const char* value(const ::fastech_io::GetIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastech_io::GetIOResponse> should match
// service_traits::DataType< ::fastech_io::GetIO >
template<>
struct DataType< ::fastech_io::GetIOResponse>
{
  static const char* value()
  {
    return DataType< ::fastech_io::GetIO >::value();
  }
  static const char* value(const ::fastech_io::GetIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FASTECH_IO_MESSAGE_GETIO_H
