// Generated by gencpp from file fastech_io/GetIOResponse.msg
// DO NOT EDIT!


#ifndef FASTECH_IO_MESSAGE_GETIORESPONSE_H
#define FASTECH_IO_MESSAGE_GETIORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fastech_io
{
template <class ContainerAllocator>
struct GetIOResponse_
{
  typedef GetIOResponse_<ContainerAllocator> Type;

  GetIOResponse_()
    : name()
    , status_set(false)
    , output_voltage(0)  {
    }
  GetIOResponse_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , status_set(false)
    , output_voltage(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint8_t _status_set_type;
  _status_set_type status_set;

   typedef int64_t _output_voltage_type;
  _output_voltage_type output_voltage;





  typedef boost::shared_ptr< ::fastech_io::GetIOResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fastech_io::GetIOResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetIOResponse_

typedef ::fastech_io::GetIOResponse_<std::allocator<void> > GetIOResponse;

typedef boost::shared_ptr< ::fastech_io::GetIOResponse > GetIOResponsePtr;
typedef boost::shared_ptr< ::fastech_io::GetIOResponse const> GetIOResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fastech_io::GetIOResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fastech_io::GetIOResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fastech_io::GetIOResponse_<ContainerAllocator1> & lhs, const ::fastech_io::GetIOResponse_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.status_set == rhs.status_set &&
    lhs.output_voltage == rhs.output_voltage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fastech_io::GetIOResponse_<ContainerAllocator1> & lhs, const ::fastech_io::GetIOResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fastech_io

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fastech_io::GetIOResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fastech_io::GetIOResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastech_io::GetIOResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastech_io::GetIOResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastech_io::GetIOResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastech_io::GetIOResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fastech_io::GetIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d4d261b4d34e979bf1f8d9fc9f93527";
  }

  static const char* value(const ::fastech_io::GetIOResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d4d261b4d34e979ULL;
  static const uint64_t static_value2 = 0xbf1f8d9fc9f93527ULL;
};

template<class ContainerAllocator>
struct DataType< ::fastech_io::GetIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fastech_io/GetIOResponse";
  }

  static const char* value(const ::fastech_io::GetIOResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fastech_io::GetIOResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"bool status_set\n"
"int64 output_voltage\n"
"\n"
;
  }

  static const char* value(const ::fastech_io::GetIOResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fastech_io::GetIOResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.status_set);
      stream.next(m.output_voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetIOResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fastech_io::GetIOResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fastech_io::GetIOResponse_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "status_set: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status_set);
    s << indent << "output_voltage: ";
    Printer<int64_t>::stream(s, indent + "  ", v.output_voltage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FASTECH_IO_MESSAGE_GETIORESPONSE_H
