// Generated by gencpp from file fastech_io/GetIORequest.msg
// DO NOT EDIT!


#ifndef FASTECH_IO_MESSAGE_GETIOREQUEST_H
#define FASTECH_IO_MESSAGE_GETIOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fastech_io
{
template <class ContainerAllocator>
struct GetIORequest_
{
  typedef GetIORequest_<ContainerAllocator> Type;

  GetIORequest_()
    : pin(0)  {
    }
  GetIORequest_(const ContainerAllocator& _alloc)
    : pin(0)  {
  (void)_alloc;
    }



   typedef int64_t _pin_type;
  _pin_type pin;





  typedef boost::shared_ptr< ::fastech_io::GetIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fastech_io::GetIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetIORequest_

typedef ::fastech_io::GetIORequest_<std::allocator<void> > GetIORequest;

typedef boost::shared_ptr< ::fastech_io::GetIORequest > GetIORequestPtr;
typedef boost::shared_ptr< ::fastech_io::GetIORequest const> GetIORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fastech_io::GetIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fastech_io::GetIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fastech_io::GetIORequest_<ContainerAllocator1> & lhs, const ::fastech_io::GetIORequest_<ContainerAllocator2> & rhs)
{
  return lhs.pin == rhs.pin;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fastech_io::GetIORequest_<ContainerAllocator1> & lhs, const ::fastech_io::GetIORequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fastech_io

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fastech_io::GetIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fastech_io::GetIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastech_io::GetIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastech_io::GetIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastech_io::GetIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastech_io::GetIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fastech_io::GetIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13ce2e1fd6796d00dec37deecb854c69";
  }

  static const char* value(const ::fastech_io::GetIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13ce2e1fd6796d00ULL;
  static const uint64_t static_value2 = 0xdec37deecb854c69ULL;
};

template<class ContainerAllocator>
struct DataType< ::fastech_io::GetIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fastech_io/GetIORequest";
  }

  static const char* value(const ::fastech_io::GetIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fastech_io::GetIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 pin\n"
;
  }

  static const char* value(const ::fastech_io::GetIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fastech_io::GetIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fastech_io::GetIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fastech_io::GetIORequest_<ContainerAllocator>& v)
  {
    s << indent << "pin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.pin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FASTECH_IO_MESSAGE_GETIOREQUEST_H
