# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from agv_msgs/HmiControl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class HmiControl(genpy.Message):
  _md5sum = "0a758689cc2994c3e06241914d97ca23"
  _type = "agv_msgs/HmiControl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
bool ChangeDirection
int8 RunType
int8 TurnType
int8 RotateType
float32 MaxSpeedSet
float32 MinSpeedSet
int8 Sound"""
  __slots__ = ['stamp','ChangeDirection','RunType','TurnType','RotateType','MaxSpeedSet','MinSpeedSet','Sound']
  _slot_types = ['time','bool','int8','int8','int8','float32','float32','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,ChangeDirection,RunType,TurnType,RotateType,MaxSpeedSet,MinSpeedSet,Sound

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HmiControl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.ChangeDirection is None:
        self.ChangeDirection = False
      if self.RunType is None:
        self.RunType = 0
      if self.TurnType is None:
        self.TurnType = 0
      if self.RotateType is None:
        self.RotateType = 0
      if self.MaxSpeedSet is None:
        self.MaxSpeedSet = 0.
      if self.MinSpeedSet is None:
        self.MinSpeedSet = 0.
      if self.Sound is None:
        self.Sound = 0
    else:
      self.stamp = genpy.Time()
      self.ChangeDirection = False
      self.RunType = 0
      self.TurnType = 0
      self.RotateType = 0
      self.MaxSpeedSet = 0.
      self.MinSpeedSet = 0.
      self.Sound = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2IB3b2fb().pack(_x.stamp.secs, _x.stamp.nsecs, _x.ChangeDirection, _x.RunType, _x.TurnType, _x.RotateType, _x.MaxSpeedSet, _x.MinSpeedSet, _x.Sound))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 21
      (_x.stamp.secs, _x.stamp.nsecs, _x.ChangeDirection, _x.RunType, _x.TurnType, _x.RotateType, _x.MaxSpeedSet, _x.MinSpeedSet, _x.Sound,) = _get_struct_2IB3b2fb().unpack(str[start:end])
      self.ChangeDirection = bool(self.ChangeDirection)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2IB3b2fb().pack(_x.stamp.secs, _x.stamp.nsecs, _x.ChangeDirection, _x.RunType, _x.TurnType, _x.RotateType, _x.MaxSpeedSet, _x.MinSpeedSet, _x.Sound))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 21
      (_x.stamp.secs, _x.stamp.nsecs, _x.ChangeDirection, _x.RunType, _x.TurnType, _x.RotateType, _x.MaxSpeedSet, _x.MinSpeedSet, _x.Sound,) = _get_struct_2IB3b2fb().unpack(str[start:end])
      self.ChangeDirection = bool(self.ChangeDirection)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2IB3b2fb = None
def _get_struct_2IB3b2fb():
    global _struct_2IB3b2fb
    if _struct_2IB3b2fb is None:
        _struct_2IB3b2fb = struct.Struct("<2IB3b2fb")
    return _struct_2IB3b2fb
