// Generated by gencpp from file tuw_multi_robot_msgs/RobotInfoArray.msg
// DO NOT EDIT!


#ifndef TUW_MULTI_ROBOT_MSGS_MESSAGE_ROBOTINFOARRAY_H
#define TUW_MULTI_ROBOT_MSGS_MESSAGE_ROBOTINFOARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tuw_multi_robot_msgs/RobotInfo.h>

namespace tuw_multi_robot_msgs
{
template <class ContainerAllocator>
struct RobotInfoArray_
{
  typedef RobotInfoArray_<ContainerAllocator> Type;

  RobotInfoArray_()
    : header()
    , robot_info()  {
    }
  RobotInfoArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::tuw_multi_robot_msgs::RobotInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tuw_multi_robot_msgs::RobotInfo_<ContainerAllocator> >> _robot_info_type;
  _robot_info_type robot_info;





  typedef boost::shared_ptr< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> const> ConstPtr;

}; // struct RobotInfoArray_

typedef ::tuw_multi_robot_msgs::RobotInfoArray_<std::allocator<void> > RobotInfoArray;

typedef boost::shared_ptr< ::tuw_multi_robot_msgs::RobotInfoArray > RobotInfoArrayPtr;
typedef boost::shared_ptr< ::tuw_multi_robot_msgs::RobotInfoArray const> RobotInfoArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator1> & lhs, const ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot_info == rhs.robot_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator1> & lhs, const ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tuw_multi_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8499af4683f82d8a5f5431edfe73ca8f";
  }

  static const char* value(const ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8499af4683f82d8aULL;
  static const uint64_t static_value2 = 0x5f5431edfe73ca8fULL;
};

template<class ContainerAllocator>
struct DataType< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tuw_multi_robot_msgs/RobotInfoArray";
  }

  static const char* value(const ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header # time of route generation\n"
"RobotInfo[] robot_info\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tuw_multi_robot_msgs/RobotInfo\n"
"#################################################################\n"
"## Presents dynamic parameters of a robot\n"
"#################################################################\n"
"\n"
"Header header                            # the creation time\n"
"string robot_name                        # the name of the robot (used in preconditions and topics)\n"
"geometry_msgs/PoseWithCovariance pose    # the robots current pose within the frame related to the msgs header\n"
"geometry_msgs/Twist velocity             # velocity of the robot (linear and angular)\n"
"int32 shape                              # the shape of the robots (see enums)\n"
"uint32 layout_map\n"
"float32[] shape_variables                # shape variables to define width height, ...\n"
"RoutePrecondition sync                   # the current position in the last received plan (-1 means none)\n"
"string   mode                             # the mode of operation\n"
"string   status                           # the status of the robot\n"
"string detail_status\n"
"int32   good_id                          # the good id attached to the robot\n"
"int32   order_id                         # the order id scheduled to this robot (-1: none)\n"
"int32   order_status                     # the status of the assigned order\n"
"\n"
"# mode\n"
"int32 MODE_NA = 0                   # undefined mode\n"
"int32 MODE_IDLE = 1                 # robot is idle\n"
"int32 MODE_SEGMENT_FOLLOWING = 2    # robot is in mode segment following\n"
"int32 MODE_PICKUP = 3               # robot is picking up goods\n"
"\n"
"# status\n"
"int32 STATUS_DRIVING = 0             # robot is driving\n"
"int32 STATUS_STOPPED = 1            # robot has stopped\n"
"int32 STATUS_DONE = 2               # robot has finished its last job\n"
"int32 STATUS_BROKEN = 3             # robot is broken and not ready for any task\n"
"\n"
"# good_id\n"
"int32 GOOD_EMPTY = -1               # no goods attached\n"
"int32 GOOD_NA = -2                  # undefined good\n"
"\n"
"# shape\n"
"int32 SHAPE_CIRCLE = 0                 # robot is in shape of a circle    ShapeVars\n"
"int32 SHAPE_RECTANGLE = 1\n"
"\n"
"# order_status\n"
"int32 ORDER_NONE = 0                # no order assigned\n"
"int32 ORDER_APPROACH = 1            # the robot approaches the first station of the order\n"
"int32 ORDER_PICKUP = 2              # the robot picks up a good at the station\n"
"int32 ORDER_TRANSPORT = 3           # the robot currently transports a good from one station to another\n"
"int32 ORDER_DROP = 4                # the robot drops a good at the last station of its order, finishing the order\n"
"\n"
"bool auto_mode\n"
"bool pause\n"
"bool init_pose\n"
"bool allow_estimate_pose\n"
"string current_action_type\n"
"string direction_move\n"
"string state_move\n"
"string mission_group\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: tuw_multi_robot_msgs/RoutePrecondition\n"
"#################################################################\n"
"## Route Preconditions are used to sync robots on a route\n"
"## e.g.: Each robot publishes its current step of its route\n"
"## with such a message\n"
"## The specific segments of a route are marked with such\n"
"## preconditions to block a robot from entering a segment\n"
"## until the sync message of the other robot has the right\n"
"## route_segment_nr\n"
"#################################################################\n"
"\n"
"string robot_id                  # the robot name for the precondition\n"
"int32 current_route_segment      # the segment nr of the route executed by the given robot\n"
"uint32 current_segment_id\n"
;
  }

  static const char* value(const ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotInfoArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tuw_multi_robot_msgs::RobotInfoArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_info[]" << std::endl;
    for (size_t i = 0; i < v.robot_info.size(); ++i)
    {
      s << indent << "  robot_info[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tuw_multi_robot_msgs::RobotInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.robot_info[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUW_MULTI_ROBOT_MSGS_MESSAGE_ROBOTINFOARRAY_H
