// Generated by gencpp from file mirror_detect/ClusterArray.msg
// DO NOT EDIT!


#ifndef MIRROR_DETECT_MESSAGE_CLUSTERARRAY_H
#define MIRROR_DETECT_MESSAGE_CLUSTERARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/PointCloud2.h>
#include <mirror_detect/Cluster.h>

namespace mirror_detect
{
template <class ContainerAllocator>
struct ClusterArray_
{
  typedef ClusterArray_<ContainerAllocator> Type;

  ClusterArray_()
    : header()
    , combinedCloud()
    , clusters()  {
    }
  ClusterArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , combinedCloud(_alloc)
    , clusters(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _combinedCloud_type;
  _combinedCloud_type combinedCloud;

   typedef std::vector< ::mirror_detect::Cluster_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::mirror_detect::Cluster_<ContainerAllocator> >> _clusters_type;
  _clusters_type clusters;





  typedef boost::shared_ptr< ::mirror_detect::ClusterArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirror_detect::ClusterArray_<ContainerAllocator> const> ConstPtr;

}; // struct ClusterArray_

typedef ::mirror_detect::ClusterArray_<std::allocator<void> > ClusterArray;

typedef boost::shared_ptr< ::mirror_detect::ClusterArray > ClusterArrayPtr;
typedef boost::shared_ptr< ::mirror_detect::ClusterArray const> ClusterArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirror_detect::ClusterArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirror_detect::ClusterArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirror_detect::ClusterArray_<ContainerAllocator1> & lhs, const ::mirror_detect::ClusterArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.combinedCloud == rhs.combinedCloud &&
    lhs.clusters == rhs.clusters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirror_detect::ClusterArray_<ContainerAllocator1> & lhs, const ::mirror_detect::ClusterArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirror_detect

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirror_detect::ClusterArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirror_detect::ClusterArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirror_detect::ClusterArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirror_detect::ClusterArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirror_detect::ClusterArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirror_detect::ClusterArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirror_detect::ClusterArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e69a4a815d38b46c096c858e9129268";
  }

  static const char* value(const ::mirror_detect::ClusterArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e69a4a815d38b46ULL;
  static const uint64_t static_value2 = 0xc096c858e9129268ULL;
};

template<class ContainerAllocator>
struct DataType< ::mirror_detect::ClusterArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirror_detect/ClusterArray";
  }

  static const char* value(const ::mirror_detect::ClusterArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirror_detect::ClusterArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"sensor_msgs/PointCloud2 combinedCloud\n"
"mirror_detect/Cluster[] clusters\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: mirror_detect/Cluster\n"
"std_msgs/Header header\n"
"sensor_msgs/PointCloud2 cloud\n"
"pcl_msgs/PointIndices points\n"
"mirror_detect/BoundingBox bbox\n"
"std_msgs/Int32 clusterID\n"
"mirror_detect/LineArray lines\n"
"mirror_detect/ICP icp\n"
"sensor_msgs/PointCloud2 icpCombinedCloud\n"
"std_msgs/Bool isDock\n"
"std_msgs/Bool potentialDock\n"
"\n"
"================================================================================\n"
"MSG: pcl_msgs/PointIndices\n"
"Header header\n"
"int32[] indices\n"
"\n"
"\n"
"================================================================================\n"
"MSG: mirror_detect/BoundingBox\n"
"std_msgs/Header header\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Point min\n"
"geometry_msgs/Point max\n"
"geometry_msgs/Vector3 dimensions\n"
"visualization_msgs/Marker marker\n"
"float64 area\n"
"float64 volume\n"
"uint32 label\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: visualization_msgs/Marker\n"
"# See http://www.ros.org/wiki/rviz/DisplayTypes/Marker and http://www.ros.org/wiki/rviz/Tutorials/Markers%3A%20Basic%20Shapes for more information on using this message with rviz\n"
"\n"
"uint8 ARROW=0\n"
"uint8 CUBE=1\n"
"uint8 SPHERE=2\n"
"uint8 CYLINDER=3\n"
"uint8 LINE_STRIP=4\n"
"uint8 LINE_LIST=5\n"
"uint8 CUBE_LIST=6\n"
"uint8 SPHERE_LIST=7\n"
"uint8 POINTS=8\n"
"uint8 TEXT_VIEW_FACING=9\n"
"uint8 MESH_RESOURCE=10\n"
"uint8 TRIANGLE_LIST=11\n"
"\n"
"uint8 ADD=0\n"
"uint8 MODIFY=0\n"
"uint8 DELETE=2\n"
"uint8 DELETEALL=3\n"
"\n"
"Header header                        # header for time/frame information\n"
"string ns                            # Namespace to place this object in... used in conjunction with id to create a unique name for the object\n"
"int32 id 		                         # object ID useful in conjunction with the namespace for manipulating and deleting the object later\n"
"int32 type 		                       # Type of object\n"
"int32 action 	                       # 0 add/modify an object, 1 (deprecated), 2 deletes an object, 3 deletes all objects\n"
"geometry_msgs/Pose pose                 # Pose of the object\n"
"geometry_msgs/Vector3 scale             # Scale of the object 1,1,1 means default (usually 1 meter square)\n"
"std_msgs/ColorRGBA color             # Color [0.0-1.0]\n"
"duration lifetime                    # How long the object should last before being automatically deleted.  0 means forever\n"
"bool frame_locked                    # If this marker should be frame-locked, i.e. retransformed into its frame every timestep\n"
"\n"
"#Only used if the type specified has some use for them (eg. POINTS, LINE_STRIP, ...)\n"
"geometry_msgs/Point[] points\n"
"#Only used if the type specified has some use for them (eg. POINTS, LINE_STRIP, ...)\n"
"#number of colors must either be 0 or equal to the number of points\n"
"#NOTE: alpha is not yet used\n"
"std_msgs/ColorRGBA[] colors\n"
"\n"
"# NOTE: only used for text markers\n"
"string text\n"
"\n"
"# NOTE: only used for MESH_RESOURCE markers\n"
"string mesh_resource\n"
"bool mesh_use_embedded_materials\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/ColorRGBA\n"
"float32 r\n"
"float32 g\n"
"float32 b\n"
"float32 a\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
"================================================================================\n"
"MSG: mirror_detect/LineArray\n"
"std_msgs/Header header\n"
"sensor_msgs/PointCloud2 combinedCloud\n"
"mirror_detect/Line[] lines\n"
"\n"
"================================================================================\n"
"MSG: mirror_detect/Line\n"
"std_msgs/Header header\n"
"sensor_msgs/PointCloud2 cloud\n"
"pcl_msgs/PointIndices points\n"
"pcl_msgs/ModelCoefficients coefficients\n"
"geometry_msgs/Pose centroid\n"
"std_msgs/Float32 length\n"
"std_msgs/Int32 clusterID\n"
"std_msgs/Int32 lineID\n"
"visualization_msgs/Marker marker\n"
"\n"
"================================================================================\n"
"MSG: pcl_msgs/ModelCoefficients\n"
"Header header\n"
"float32[] values\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
"================================================================================\n"
"MSG: mirror_detect/ICP\n"
"std_msgs/Header header\n"
"geometry_msgs/PoseStamped poseStamped\n"
"geometry_msgs/TransformStamped transformStamped\n"
"visualization_msgs/Marker poseTextMarker\n"
"float64 score\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TransformStamped\n"
"# This expresses a transform from coordinate frame header.frame_id\n"
"# to the coordinate frame child_frame_id\n"
"#\n"
"# This message is mostly used by the \n"
"# <a href=\"http://wiki.ros.org/tf\">tf</a> package. \n"
"# See its documentation for more information.\n"
"\n"
"Header header\n"
"string child_frame_id # the frame id of the child frame\n"
"Transform transform\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::mirror_detect::ClusterArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirror_detect::ClusterArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.combinedCloud);
      stream.next(m.clusters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClusterArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirror_detect::ClusterArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirror_detect::ClusterArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "combinedCloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.combinedCloud);
    s << indent << "clusters[]" << std::endl;
    for (size_t i = 0; i < v.clusters.size(); ++i)
    {
      s << indent << "  clusters[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mirror_detect::Cluster_<ContainerAllocator> >::stream(s, indent + "    ", v.clusters[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRROR_DETECT_MESSAGE_CLUSTERARRAY_H
