// Generated by gencpp from file mirror_detect/HubServiceResponse.msg
// DO NOT EDIT!


#ifndef MIRROR_DETECT_MESSAGE_HUBSERVICERESPONSE_H
#define MIRROR_DETECT_MESSAGE_HUBSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirror_detect
{
template <class ContainerAllocator>
struct HubServiceResponse_
{
  typedef HubServiceResponse_<ContainerAllocator> Type;

  HubServiceResponse_()
    : success(false)  {
    }
  HubServiceResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::mirror_detect::HubServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirror_detect::HubServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HubServiceResponse_

typedef ::mirror_detect::HubServiceResponse_<std::allocator<void> > HubServiceResponse;

typedef boost::shared_ptr< ::mirror_detect::HubServiceResponse > HubServiceResponsePtr;
typedef boost::shared_ptr< ::mirror_detect::HubServiceResponse const> HubServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirror_detect::HubServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirror_detect::HubServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirror_detect::HubServiceResponse_<ContainerAllocator1> & lhs, const ::mirror_detect::HubServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirror_detect::HubServiceResponse_<ContainerAllocator1> & lhs, const ::mirror_detect::HubServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirror_detect

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirror_detect::HubServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirror_detect::HubServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirror_detect::HubServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirror_detect::HubServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirror_detect::HubServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirror_detect::HubServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirror_detect::HubServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::mirror_detect::HubServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::mirror_detect::HubServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirror_detect/HubServiceResponse";
  }

  static const char* value(const ::mirror_detect::HubServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirror_detect::HubServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::mirror_detect::HubServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirror_detect::HubServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HubServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirror_detect::HubServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirror_detect::HubServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRROR_DETECT_MESSAGE_HUBSERVICERESPONSE_H
