// Generated by gencpp from file mirror_detect/MinMaxPoint.msg
// DO NOT EDIT!


#ifndef MIRROR_DETECT_MESSAGE_MINMAXPOINT_H
#define MIRROR_DETECT_MESSAGE_MINMAXPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace mirror_detect
{
template <class ContainerAllocator>
struct MinMaxPoint_
{
  typedef MinMaxPoint_<ContainerAllocator> Type;

  MinMaxPoint_()
    : min()
    , max()  {
    }
  MinMaxPoint_(const ContainerAllocator& _alloc)
    : min(_alloc)
    , max(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _min_type;
  _min_type min;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _max_type;
  _max_type max;





  typedef boost::shared_ptr< ::mirror_detect::MinMaxPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirror_detect::MinMaxPoint_<ContainerAllocator> const> ConstPtr;

}; // struct MinMaxPoint_

typedef ::mirror_detect::MinMaxPoint_<std::allocator<void> > MinMaxPoint;

typedef boost::shared_ptr< ::mirror_detect::MinMaxPoint > MinMaxPointPtr;
typedef boost::shared_ptr< ::mirror_detect::MinMaxPoint const> MinMaxPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirror_detect::MinMaxPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirror_detect::MinMaxPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirror_detect::MinMaxPoint_<ContainerAllocator1> & lhs, const ::mirror_detect::MinMaxPoint_<ContainerAllocator2> & rhs)
{
  return lhs.min == rhs.min &&
    lhs.max == rhs.max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirror_detect::MinMaxPoint_<ContainerAllocator1> & lhs, const ::mirror_detect::MinMaxPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirror_detect

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirror_detect::MinMaxPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirror_detect::MinMaxPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirror_detect::MinMaxPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirror_detect::MinMaxPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirror_detect::MinMaxPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirror_detect::MinMaxPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirror_detect::MinMaxPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93aa3d73b866f04880927745f4aab303";
  }

  static const char* value(const ::mirror_detect::MinMaxPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93aa3d73b866f048ULL;
  static const uint64_t static_value2 = 0x80927745f4aab303ULL;
};

template<class ContainerAllocator>
struct DataType< ::mirror_detect::MinMaxPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirror_detect/MinMaxPoint";
  }

  static const char* value(const ::mirror_detect::MinMaxPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirror_detect::MinMaxPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point min\n"
"geometry_msgs/Point max\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mirror_detect::MinMaxPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirror_detect::MinMaxPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min);
      stream.next(m.max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MinMaxPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirror_detect::MinMaxPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirror_detect::MinMaxPoint_<ContainerAllocator>& v)
  {
    s << indent << "min: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.min);
    s << indent << "max: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRROR_DETECT_MESSAGE_MINMAXPOINT_H
