// Generated by gencpp from file mission_manager/CheckPositionStatusFeedback.msg
// DO NOT EDIT!


#ifndef MISSION_MANAGER_MESSAGE_CHECKPOSITIONSTATUSFEEDBACK_H
#define MISSION_MANAGER_MESSAGE_CHECKPOSITIONSTATUSFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mission_manager
{
template <class ContainerAllocator>
struct CheckPositionStatusFeedback_
{
  typedef CheckPositionStatusFeedback_<ContainerAllocator> Type;

  CheckPositionStatusFeedback_()
    : rest_time(0.0)  {
    }
  CheckPositionStatusFeedback_(const ContainerAllocator& _alloc)
    : rest_time(0.0)  {
  (void)_alloc;
    }



   typedef float _rest_time_type;
  _rest_time_type rest_time;





  typedef boost::shared_ptr< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CheckPositionStatusFeedback_

typedef ::mission_manager::CheckPositionStatusFeedback_<std::allocator<void> > CheckPositionStatusFeedback;

typedef boost::shared_ptr< ::mission_manager::CheckPositionStatusFeedback > CheckPositionStatusFeedbackPtr;
typedef boost::shared_ptr< ::mission_manager::CheckPositionStatusFeedback const> CheckPositionStatusFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator1> & lhs, const ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.rest_time == rhs.rest_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator1> & lhs, const ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mission_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80e5059cedd56925a543afc9b5aadef4";
  }

  static const char* value(const ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80e5059cedd56925ULL;
  static const uint64_t static_value2 = 0xa543afc9b5aadef4ULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mission_manager/CheckPositionStatusFeedback";
  }

  static const char* value(const ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float32 rest_time\n"
;
  }

  static const char* value(const ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rest_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckPositionStatusFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mission_manager::CheckPositionStatusFeedback_<ContainerAllocator>& v)
  {
    s << indent << "rest_time: ";
    Printer<float>::stream(s, indent + "  ", v.rest_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MISSION_MANAGER_MESSAGE_CHECKPOSITIONSTATUSFEEDBACK_H
