// Generated by gencpp from file mission_manager/MissionFeedback.msg
// DO NOT EDIT!


#ifndef MISSION_MANAGER_MESSAGE_MISSIONFEEDBACK_H
#define MISSION_MANAGER_MESSAGE_MISSIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mission_manager
{
template <class ContainerAllocator>
struct MissionFeedback_
{
  typedef MissionFeedback_<ContainerAllocator> Type;

  MissionFeedback_()
    : action()  {
    }
  MissionFeedback_(const ContainerAllocator& _alloc)
    : action(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::mission_manager::MissionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_manager::MissionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MissionFeedback_

typedef ::mission_manager::MissionFeedback_<std::allocator<void> > MissionFeedback;

typedef boost::shared_ptr< ::mission_manager::MissionFeedback > MissionFeedbackPtr;
typedef boost::shared_ptr< ::mission_manager::MissionFeedback const> MissionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mission_manager::MissionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mission_manager::MissionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mission_manager::MissionFeedback_<ContainerAllocator1> & lhs, const ::mission_manager::MissionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mission_manager::MissionFeedback_<ContainerAllocator1> & lhs, const ::mission_manager::MissionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mission_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mission_manager::MissionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_manager::MissionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_manager::MissionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_manager::MissionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_manager::MissionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_manager::MissionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mission_manager::MissionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7757aad79fa343e61bc69ed7f1b7666d";
  }

  static const char* value(const ::mission_manager::MissionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7757aad79fa343e6ULL;
  static const uint64_t static_value2 = 0x1bc69ed7f1b7666dULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_manager::MissionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mission_manager/MissionFeedback";
  }

  static const char* value(const ::mission_manager::MissionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mission_manager::MissionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"string action\n"
;
  }

  static const char* value(const ::mission_manager::MissionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mission_manager::MissionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mission_manager::MissionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mission_manager::MissionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MISSION_MANAGER_MESSAGE_MISSIONFEEDBACK_H
