// Generated by gencpp from file mission_manager/MissionResult.msg
// DO NOT EDIT!


#ifndef MISSION_MANAGER_MESSAGE_MISSIONRESULT_H
#define MISSION_MANAGER_MESSAGE_MISSIONRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mission_manager
{
template <class ContainerAllocator>
struct MissionResult_
{
  typedef MissionResult_<ContainerAllocator> Type;

  MissionResult_()
    : total_time(0.0)  {
    }
  MissionResult_(const ContainerAllocator& _alloc)
    : total_time(0.0)  {
  (void)_alloc;
    }



   typedef double _total_time_type;
  _total_time_type total_time;





  typedef boost::shared_ptr< ::mission_manager::MissionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_manager::MissionResult_<ContainerAllocator> const> ConstPtr;

}; // struct MissionResult_

typedef ::mission_manager::MissionResult_<std::allocator<void> > MissionResult;

typedef boost::shared_ptr< ::mission_manager::MissionResult > MissionResultPtr;
typedef boost::shared_ptr< ::mission_manager::MissionResult const> MissionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mission_manager::MissionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mission_manager::MissionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mission_manager::MissionResult_<ContainerAllocator1> & lhs, const ::mission_manager::MissionResult_<ContainerAllocator2> & rhs)
{
  return lhs.total_time == rhs.total_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mission_manager::MissionResult_<ContainerAllocator1> & lhs, const ::mission_manager::MissionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mission_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mission_manager::MissionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_manager::MissionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_manager::MissionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_manager::MissionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_manager::MissionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_manager::MissionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mission_manager::MissionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f5f6b9813dfec2076bf5e88b01000f9";
  }

  static const char* value(const ::mission_manager::MissionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f5f6b9813dfec20ULL;
  static const uint64_t static_value2 = 0x76bf5e88b01000f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_manager::MissionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mission_manager/MissionResult";
  }

  static const char* value(const ::mission_manager::MissionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mission_manager::MissionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result\n"
"float64 total_time\n"
"\n"
;
  }

  static const char* value(const ::mission_manager::MissionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mission_manager::MissionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mission_manager::MissionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mission_manager::MissionResult_<ContainerAllocator>& v)
  {
    s << indent << "total_time: ";
    Printer<double>::stream(s, indent + "  ", v.total_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MISSION_MANAGER_MESSAGE_MISSIONRESULT_H
