(cl:in-package tuw_multi_robot_msgs-srv)
(cl:export '(ROBOT_NAME-VAL
          ROBOT_NAME
          DETAIL_STATUS_RUN_PAUSE_BY_ROUTE-VAL
          DETAIL_STATUS_RUN_PAUSE_BY_ROUTE
          DETAIL_STATUS_RUN_PAUSE_BY_DETECT_COLLISION-VAL
          DETAIL_STATUS_RUN_PAUSE_BY_DETECT_COLLISION
          IS_PAUSE_BY_ROUTE-VAL
          IS_PAUSE_BY_ROUTE
          IS_PAUSE_BY_DETECT_COLLISION-VAL
          IS_PAUSE_BY_DETECT_COLLISION
))