(cl:defpackage tuw_multi_robot_msgs-srv
  (:use )
  (:export
   "GETROBOTSTATUS"
   "<GETROBOTSTATUS-REQUEST>"
   "GETROBOTSTATUS-REQUEST"
   "<GETROBOTSTATUS-RESPONSE>"
   "GETROBOTSTATUS-RESPONSE"
   "STATIONMANAGERCONTROLPROTOCOL"
   "<STATIONMANAGERCONTROLPROTOCOL-REQUEST>"
   "STATIONMANAGERCONTROLPROTOCOL-REQUEST"
   "<STATIONMANAGERCONTROLPROTOCOL-RESPONSE>"
   "STATIONMANAGERCONTROLPROTOCOL-RESPONSE"
   "STATIONMANAGERSTATIONPROTOCOL"
   "<STATIONMANAGERSTATIONPROTOCOL-REQUEST>"
   "STATIONMANAGERSTATIONPROTOCOL-REQUEST"
   "<STATIONMANAGERSTATIONPROTOCOL-RESPONSE>"
   "STATIONMANAGERSTATIONPROTOCOL-RESPONSE"
   "REQUESTGOAL"
   "<REQUESTGOAL-REQUEST>"
   "REQUESTGOAL-REQUEST"
   "<REQUESTGOAL-RESPONSE>"
   "REQUESTGOAL-RESPONSE"
  ))

