; Auto-generated. Do not edit!


(cl:in-package docking-msg)


;//! \htmlinclude DockingResult.msg.html

(cl:defclass <DockingResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass DockingResult (<DockingResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DockingResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DockingResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name docking-msg:<DockingResult> is deprecated: use docking-msg:DockingResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <DockingResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader docking-msg:success-val is deprecated.  Use docking-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DockingResult>) ostream)
  "Serializes a message object of type '<DockingResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DockingResult>) istream)
  "Deserializes a message object of type '<DockingResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DockingResult>)))
  "Returns string type for a message object of type '<DockingResult>"
  "docking/DockingResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DockingResult)))
  "Returns string type for a message object of type 'DockingResult"
  "docking/DockingResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DockingResult>)))
  "Returns md5sum for a message object of type '<DockingResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DockingResult)))
  "Returns md5sum for a message object of type 'DockingResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DockingResult>)))
  "Returns full string definition for message of type '<DockingResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success ~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DockingResult)))
  "Returns full string definition for message of type 'DockingResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success ~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DockingResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DockingResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DockingResult
    (cl:cons ':success (success msg))
))
