(cl:defpackage sound_control-msg
  (:use )
  (:export
   "<SOUNDCONTROLACTION>"
   "SOUNDCONTROLACTION"
   "<SOUNDCONTROLACTIONFEEDBACK>"
   "SOUNDCONTROLACTIONFEEDBACK"
   "<SOUNDCONTROLACTIONGOAL>"
   "SOUNDCONTROLACTIONGOAL"
   "<SOUNDCONTROLACTIONRESULT>"
   "SOUNDCONTROLACTIONRESULT"
   "<SOUNDCONTROLFEEDBACK>"
   "SOUNDCONTROLFEEDBACK"
   "<SOUNDCONTROLGOAL>"
   "SOUNDCONTROLGOAL"
   "<SOUNDCONTROLRESULT>"
   "SOUNDCONTROLRESULT"
  ))

