; Auto-generated. Do not edit!


(cl:in-package sound_control-msg)


;//! \htmlinclude SoundControlFeedback.msg.html

(cl:defclass <SoundControlFeedback> (roslisp-msg-protocol:ros-message)
  ((Feedback
    :reader Feedback
    :initarg :Feedback
    :type cl:string
    :initform ""))
)

(cl:defclass SoundControlFeedback (<SoundControlFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SoundControlFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SoundControlFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sound_control-msg:<SoundControlFeedback> is deprecated: use sound_control-msg:SoundControlFeedback instead.")))

(cl:ensure-generic-function 'Feedback-val :lambda-list '(m))
(cl:defmethod Feedback-val ((m <SoundControlFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sound_control-msg:Feedback-val is deprecated.  Use sound_control-msg:Feedback instead.")
  (Feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SoundControlFeedback>) ostream)
  "Serializes a message object of type '<SoundControlFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'Feedback))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'Feedback))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SoundControlFeedback>) istream)
  "Deserializes a message object of type '<SoundControlFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'Feedback) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'Feedback) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SoundControlFeedback>)))
  "Returns string type for a message object of type '<SoundControlFeedback>"
  "sound_control/SoundControlFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SoundControlFeedback)))
  "Returns string type for a message object of type 'SoundControlFeedback"
  "sound_control/SoundControlFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SoundControlFeedback>)))
  "Returns md5sum for a message object of type '<SoundControlFeedback>"
  "b93d9f2619e4939102de2e5c6f022b87")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SoundControlFeedback)))
  "Returns md5sum for a message object of type 'SoundControlFeedback"
  "b93d9f2619e4939102de2e5c6f022b87")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SoundControlFeedback>)))
  "Returns full string definition for message of type '<SoundControlFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string Feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SoundControlFeedback)))
  "Returns full string definition for message of type 'SoundControlFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string Feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SoundControlFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'Feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SoundControlFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SoundControlFeedback
    (cl:cons ':Feedback (Feedback msg))
))
