// Generated by gencpp from file arduino_serial/LiftStatus.msg
// DO NOT EDIT!


#ifndef ARDUINO_SERIAL_MESSAGE_LIFTSTATUS_H
#define ARDUINO_SERIAL_MESSAGE_LIFTSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arduino_serial
{
template <class ContainerAllocator>
struct LiftStatus_
{
  typedef LiftStatus_<ContainerAllocator> Type;

  LiftStatus_()
    : stamp()
    , sensor_max(false)
    , sensor_min(false)  {
    }
  LiftStatus_(const ContainerAllocator& _alloc)
    : stamp()
    , sensor_max(false)
    , sensor_min(false)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef uint8_t _sensor_max_type;
  _sensor_max_type sensor_max;

   typedef uint8_t _sensor_min_type;
  _sensor_min_type sensor_min;





  typedef boost::shared_ptr< ::arduino_serial::LiftStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arduino_serial::LiftStatus_<ContainerAllocator> const> ConstPtr;

}; // struct LiftStatus_

typedef ::arduino_serial::LiftStatus_<std::allocator<void> > LiftStatus;

typedef boost::shared_ptr< ::arduino_serial::LiftStatus > LiftStatusPtr;
typedef boost::shared_ptr< ::arduino_serial::LiftStatus const> LiftStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arduino_serial::LiftStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arduino_serial::LiftStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arduino_serial::LiftStatus_<ContainerAllocator1> & lhs, const ::arduino_serial::LiftStatus_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.sensor_max == rhs.sensor_max &&
    lhs.sensor_min == rhs.sensor_min;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arduino_serial::LiftStatus_<ContainerAllocator1> & lhs, const ::arduino_serial::LiftStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arduino_serial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arduino_serial::LiftStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_serial::LiftStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduino_serial::LiftStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduino_serial::LiftStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_serial::LiftStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_serial::LiftStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arduino_serial::LiftStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff08c76cb254ec9297cccc8566cbbf64";
  }

  static const char* value(const ::arduino_serial::LiftStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff08c76cb254ec92ULL;
  static const uint64_t static_value2 = 0x97cccc8566cbbf64ULL;
};

template<class ContainerAllocator>
struct DataType< ::arduino_serial::LiftStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arduino_serial/LiftStatus";
  }

  static const char* value(const ::arduino_serial::LiftStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arduino_serial::LiftStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"bool sensor_max\n"
"bool sensor_min\n"
;
  }

  static const char* value(const ::arduino_serial::LiftStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arduino_serial::LiftStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.sensor_max);
      stream.next(m.sensor_min);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiftStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arduino_serial::LiftStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arduino_serial::LiftStatus_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "sensor_max: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor_max);
    s << indent << "sensor_min: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor_min);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUINO_SERIAL_MESSAGE_LIFTSTATUS_H
