(cl:in-package tuw_multi_robot_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ROBOT_NAME-VAL
          ROBOT_NAME
          POSE-VAL
          POSE
          VELOCITY-VAL
          VELOCITY
          SHAPE-VAL
          SHAPE
          LAYOUT_MAP-VAL
          LAYOUT_MAP
          SHAPE_VARIABLES-VAL
          SHAPE_VARIABLES
          SYNC-VAL
          SYNC
          MODE-VAL
          MODE
          STATUS-VAL
          STATUS
          DETAIL_STATUS-VAL
          DETAIL_STATUS
          GOOD_ID-VAL
          GOOD_ID
          ORDER_ID-VAL
          ORDER_ID
          ORDER_STATUS-VAL
          ORDER_STATUS
          AUTO_MODE-VAL
          AUTO_MODE
          PAUSE-VAL
          PAUSE
          INIT_POSE-VAL
          INIT_POSE
          ALLOW_ESTIMATE_POSE-VAL
          ALLOW_ESTIMATE_POSE
          CURRENT_ACTION_TYPE-VAL
          CURRENT_ACTION_TYPE
          DIRECTION_MOVE-VAL
          DIRECTION_MOVE
          STATE_MOVE-VAL
          STATE_MOVE
          MISSION_GROUP-VAL
          MISSION_GROUP
))